force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>Clarity Forms Fields</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Input</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/selectors/FieldsSelector.cls
public with sharing class FieldsSelector extends fflib_SObjectSelector implements IFieldsSelector {
  public Schema.SObjectType getSObjectType() {
    return Field__mdt.sObjectType;
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Field__mdt.DeveloperName,
      Field__mdt.Level__c,
      Field__mdt.Type__c
    };
  }

  public List<Field__mdt> selectAllFields() {
    fflib_QueryFactory query = newQueryFactory();

    return (List<Field__mdt>) Database.query(query.toSOQL());
  }

  public static IFieldsSelector newInstance() {
    return (IFieldsSelector) Application.selector.newInstance(
      Field__mdt.SObjectType
    );
  }
}