mdapi-source/updated-package/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Checklist_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Checklist Group</label>
        <referenceTo>Checklist_Group__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Checklist_Group__c.object
<CustomObject>
    <label>Clarity Checklist Group</label>
    <nameField>
        <label>Checklist Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Checklist Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Checklist_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Checklist Group</label>
        <referenceTo>Checklist_Group__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/restapi/AppsResourceUnitTest.cls
@isTest
public class AppsResourceUnitTest {

	@TestSetup
	public static void setup(){
		
		List<Checklist_Group__c> groups = TestDataFactory.generateChecklistGroups(3);

		insert groups; 

		List<Form__c> forms = TestDataFactory.generateFormsWithGroup(groups); 

		upsert forms; 

		List<Account> accounts = TestDataFactory.generateApps(groups);

		insert accounts;

		Account account = new Account(
			Name = 'No Group'
		);

		insert account; 

	}

	@isTest
	public static void shouldGetApps() {

		List<Account> accounts = [SELECT Id FROM Account];

		System.assertEquals(accounts.size(), 4);
		
		RestRequest request = new RestRequest();

		request.httpMethod = 'GET';
		RestContext.request = request;

		List<App> apps = AppsResource.getApps();

		//return number of apps (accounts in this case with checklist);
		System.assertEquals(accounts.size() - 1, apps.size());

	} 
	
}