mdapi-source/updated-package/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Checklist_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Checklist Group</label>
        <referenceTo>Checklist_Group__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Checklist_Group__c.object
<CustomObject>
    <label>Clarity Checklist Group</label>
    <nameField>
        <label>Checklist Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Checklist Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Checklist_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Checklist Group</label>
        <referenceTo>Checklist_Group__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/restapi/AppsResource.cls
@RestResource(urlMapping='/v1/Apps/*')
global with sharing class AppsResource {
  @HttpGet
  global static List<App> getApps() {
    /**
     * Will query by params
     * param searchTerm
     * param geoLocation
     * param offset
     * param limit
     */

    RestRequest req = RestContext.request;
    RestResponse res = RestContext.response;

    List<Account> accounts = AccountsService.getAccountsWithChecklistGroups();
    Set<Id> checkListGroupIds = new Set<Id>();

    for (Account account : accounts) {
      checkListGroupIds.add(account.Checklist_Group__c);
    }

    List<Checklist_Group__c> checklists = ChecklistGroupsSelector.newInstance()
      .selectByIdWithForms(checkListGroupIds);
    Map<Id, Checklist_Group__c> checkListGroups = new Map<Id, Checklist_Group__c>();

    for (Checklist_Group__c checklistGroup : checklistGroups) {
      checkListGroups.put(checklistGroup.Id, checklistGroup);
    }

    List<App> apps = new List<App>();

    for (Account account : accounts) {
      Checklist_Group__c checklistGroup = checklistGroups.get(
        account.Checklist_Group__c
      );
      App app = new App();
      app.record = account;
      app.checklistGroup = checklistGroup;
      app.forms = checklist.Forms__r;
      apps.add(app);
    }

    return apps;
  }
}