mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Answer__c/Clarity_Form_Answer__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <label>Clarity Form Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Question</label>
    <referenceTo>Clarity_Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Response__c</fullName>
    <label>Clarity Form Response</label>
    <referenceTo>Clarity_Form_Response__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection__c/Clarity_Form_Connection__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Connection__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Connections</relationshipLabel>
    <relationshipName>Clarity_Form_Connections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/recordTypes/Preview.recordType-meta.xml
<RecordType>
    <fullName>Preview</fullName>
    <active>false</active>
    <label>Preview</label>
</RecordType>

force-app/main/default/classes/ClarityFormResponseTest.cls
@isTest
public class ClarityFormResponseTest {

    @testSetup
    public static void setup(){

		Clarity_Form__c form = ClarityTestDataFactory.generateForm();

		List<Clarity_Form_Question__c> questions = ClarityTestDataFactory.generateQuestions(form);

        List<Clarity_Form_Connection__c> connections = ClarityTestDataFactory.generateConnections(form,  new List<String>{ 'Opportunity' });

    }

	@isTest
	public static void shouldGetPreview() {

		Clarity_Form__c form = [SELECT Id FROM Clarity_Form__c LIMIT 1];

		Test.startTest();

			Map<String, List<sObject>> preview = ClarityFormResponse.preview(form.Id); 

		Test.stopTest();

	}

	@isTest
	public static void shouldCheckConnections() {

		Clarity_Form__c form = [SELECT Id FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		Test.startTest();

			List<Clarity_Form_Connection__c> connections = ClarityFormResponse.checkConnections(response.Id); 

		Test.stopTest();

	}

	@isTest
	public static void shouldGetConnections() {
		
		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Test.startTest();

			List<Clarity_Form_Connection__c> connections = ClarityFormResponse.getConnections(form.Name); 

		Test.stopTest();

	}

	@isTest
	public static void shouldGetRecordGroupResults() {
		
		// Clarity_Form__c form = [SELECT Id FROM Clarity_Form__c LIMIT 1];

		// Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		// Test.startTest();

		// 	Map<Id, List<sObject>> recordGroupResults = ClarityFormResponse.getRecordGroupResults(response.Id, form.Id); 

		// Test.stopTest();

	}

	@isTest
	public static void shouldCreateResponse() {
		
		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		List<Clarity_Form_Connection__c> connections = [SELECT Id FROM Clarity_Form_Connection__c];

		String sConnections = JSON.serialize(connections); 

		Test.startTest();

			Map<String, List<sObject>> create = ClarityFormResponse.create(form.Name, sConnections); 

		Test.stopTest();

	}

	@isTest
	public static void shouldEditResponse() {
		
		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		List<Clarity_Form_Connection__c> connections = [SELECT Id FROM Clarity_Form_Connection__c];

		String sConnections = JSON.serialize(connections); 

		Test.startTest();

			Map<String, List<sObject>> edit = ClarityFormResponse.edit(response.Id, sConnections);

		Test.stopTest();

	}

	@isTest
	public static void shouldSaveAnswer() {

		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		List<Clarity_Form_Question__c> questions = [SELECT Id FROM Clarity_Form_Question__c];

		Clarity_Form_Answer__c answer = new Clarity_Form_Answer__c(
			Clarity_Form_Question__c = questions[0].Id, 
			Answer__c				 = 'Test', 
			Clarity_Form_Response__c = response.Id
		);

		String sAnswer = JSON.serialize(answer); 

		Test.startTest();

			List<Clarity_Form_Answer__c> answers = ClarityFormResponse.saveAnswer(sAnswer);

		Test.stopTest();

	}

	@isTest
	public static void shouldSaveResponse() {

		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		List<Clarity_Form_Question__c> questions = [SELECT Id FROM Clarity_Form_Question__c];

		List<Clarity_Form_Answer__c> answers = new List<Clarity_Form_Answer__c>(); 

		Clarity_Form_Answer__c answer = new Clarity_Form_Answer__c(
			Clarity_Form_Question__c = questions[0].Id, 
			Answer__c				 = 'Test',
			Clarity_Form_Response__c = response.Id
		);

		answers.add(answer); 

		String answerValues = JSON.serialize(answers); 

		List<String> holdAnswers = new List<String>{ '', answerValues, response.Id }; 

		Test.startTest();

			List<String> save = ClarityFormResponse.save(holdAnswers);

		Test.stopTest();

	}

	@isTest
	public static void shouldSubmitResponse() {

		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		List<Clarity_Form_Question__c> questions = [SELECT Id FROM Clarity_Form_Question__c];

		Clarity_Form_Answer__c answer = new Clarity_Form_Answer__c(
			Clarity_Form_Question__c = questions[0].Id, 
			Answer__c				 = 'Test',
			Clarity_Form_Response__c = response.Id
		);

		String answerValue = JSON.serialize(answer); 

		Test.startTest();

			List<Clarity_Form_Answer__c> answers = ClarityFormResponse.saveAnswer(answerValue);

		Test.stopTest();	

	}

	@isTest
	public static void shouldReturnLookSearchResults() {
		
		List<String> searchItems = new List<String>{ 'Test', 'Account', '' };

		Test.startTest();

			List<ClarityFormResponse.LookupResult> search = ClarityFormResponse.search(searchItems);

		Test.stopTest();
	}

	@isTest
	public static void shouldCreateRecord() {

		Clarity_Form__c form = [SELECT Id, Name FROM Clarity_Form__c LIMIT 1];

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

		Clarity_Form_Question__c recordGroup = ClarityTestDataFactory.generateRecordGroup(form);

		String records = '[{"field":"OpportunityId","value":"2","type":"REFERENCE"},{"field":"Quantity","value":1,"type":"INTEGER"},{"field":"Product2Id","value":"2","type":"REFERENCE"}]';

		List<String> recordValues = new List<String>{ response.Id, recordGroup.Id, 'Opportunity', records };

		Test.startTest();

			sObject result = ClarityFormResponse.createRecord(recordValues);

		Test.stopTest();
	}

	@isTest
	public static void shouldGetRecordGroupPicklist() {
		
	}

}