mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clarity Form Responses</relationshipLabel>
        <relationshipName>Clarity_Form_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/controllers/ResponseControllerUnitTest.cls
@isTest
public class ResponseControllerUnitTest {

	@TestSetup
	public static void setup(){
		
		Form__c form = TestDataFactory.generateForm(); 

		Form__c updatedForm = FormsService.updateForm(form);

		List<Question__c> newQuestions = TestDataFactory.generateQuestions(new List<Form__c>{ form });

		List<Question__c> questions = QuestionsService.saveQuestions(newQuestions);

		updatedForm.Status__c = 'Published';

		Form__c publishedForm = FormsService.updateForm(updatedForm);

	}

	@isTest
    public static void shouldCreateResponse() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 
		
		Test.startTest();

			Response__c response = ResponseController.createResponse( existingFormId, JSON.serialize(new Map<String, String>()) );

		Test.stopTest();
		
		System.assertEquals(existingFormId, response.Form__c);

	}

	@isTest
    public static void shouldGetResponse() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		Response__c newResponse = ResponseController.createResponse( existingFormId, JSON.serialize(new Map<String, String>()) );

		Test.startTest();

			Response__c response = ResponseController.getResponse( newResponse.Id );

		Test.stopTest();

		System.assertEquals(newResponse.Id, response.Id);

	}
	
	@isTest
    public static void shouldGetResponses() {

		Account newAccount = new Account(Name = 'Test Class');

		insert newAccount;

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		Map<String, String> connectionRecordIds = new Map<String, String>{ 'Account' => newAccount.Id };

		Response__c newResponse = ResponseController.createResponse( existingFormId, JSON.serialize(connectionRecordIds) );

		Test.startTest();

			List<Response__c> responses = ResponseController.getResponses( newAccount.Id );

		Test.stopTest();

		System.assertEquals(newAccount.Id, responses[0].Account__c);

	}
	
	@isTest
    public static void shouldGetConnections() {


	}
	
	@isTest
    public static void shouldGetQuestions() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		List<Question__c> existingQuestions = [SELECT Id FROM Question__c];

		Test.startTest();

			List<Question__c> questions = ResponseController.getQuestions( existingFormId );

		Test.stopTest();

		System.assertEquals(existingQuestions.size(), questions.size());

	}
	
	@isTest
    public static void shouldSaveResponse() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		Response__c response = ResponseController.createResponse( existingFormId, JSON.serialize(new Map<String, String>()) );

		List<Question__c> questions = [SELECT Id FROM Question__c LIMIT 3];
		
		List<Answer__c> answers = TestDataFactory.generateAnswers(response, questions);

		String sAnswers = JSON.serialize(answers);

		Test.startTest();

			Id savedResponseId = ResponseController.saveResponse( response.Id, sAnswers, 'In Progress' );

		Test.stopTest();

		List<Answer__c> updatedAnswers = [SELECT Id FROM Answer__c WHERE Response__c =: savedResponseId];

		System.assertEquals(answers.size(), updatedAnswers.size());

	}
	
	@isTest
    public static void shouldFormSearch() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		Test.startTest();

			List<LookupSearchResult> results = ResponseController.formSearch( 'Clarity', new List<String>() );

		Test.stopTest();

		System.assertEquals(results[0].id, existingFormId);

	}
	
	@isTest
    public static void shouldConnectionSearch() {

		Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

		Id existingFormId = existingForm.Id; 

		Account newAccount = new Account(Name = 'Test Class');
		
		insert newAccount;

		Test.startTest();

			List<LookupSearchResult> results = ResponseController.connectionSearch( 'Test', new List<String>(), 'Account');

		Test.stopTest();

		System.assertEquals(results[0].id, newAccount.Id);

    }
}