mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FreeText_Type__c</fullName>
        <label>Free Text Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Header</fullName>
                </value>
                <value>
                    <fullName>Paragraph</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logic__c</fullName>
        <defaultValue>&quot;AND&quot;</defaultValue>
        <label>Logic</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lookup__c</fullName>
        <label>Lookup</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Length__c</fullName>
        <defaultValue>100</defaultValue>
        <label>Max Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Range__c</fullName>
        <defaultValue>100</defaultValue>
        <label>Max Range</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Range__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Min Range</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Page</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefill_Type__c</fullName>
        <label>Prefill Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>URL Query Parameter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Group</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Record Groups</relationshipLabel>
        <relationshipName>Clarity_Form_Questions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/QuestionsSelector.cls
public class QuestionsSelector extends fflib_SObjectSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Answer__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Question__c.Id,
			Question__c.Name,
			Question__c.Title__c,
			Question__c.Type__c,
			Question__c.Order__c,
			Question__c.Lookup__c,
			Question__c.Max_Length__c,
			Question__c.Max_Range__c,
			Question__c.Min_Range__c,
			Question__c.Page__c,
			Question__c.Required__c,
			Question__c.Salesforce_Field__c,
			Question__c.Salesforce_Object__c,
			Question__c.Logic__c,
			Question__c.FreeText_Type__c,
			Question__c.Form__c,
			Question__c.Record_Group__c,
			Question__c.Prefill_Type__c
		};
	}

	public List<Question__c> selectById(Set<Id> recordIds){
		return (List<Question__c>) selectSObjectsById(recordIds);
	}

	public static IQuestionsSelector newInstance(){
		return (IQuestionsSelector) Application.selector.newInstance(Question__c.SObjectType);
	}
 
}