mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContentDocument__c</fullName>
        <label>ContentDocument</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentVersion__c</fullName>
        <label>ContentVersion</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Answer__c</fullName>
        <label>Date Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/Clarity_Form_Answer__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <label>Clarity Form Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Question</label>
    <referenceTo>Clarity_Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Response__c</fullName>
    <label>Clarity Form Response</label>
    <referenceTo>Clarity_Form_Response__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/ContentDocument__c.field-meta.xml
<CustomField>
    <fullName>ContentDocument__c</fullName>
    <label>ContentDocument</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/ContentVersion__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion__c</fullName>
    <label>ContentVersion</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection__c/Clarity_Form_Connection__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Connection__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Connections</relationshipLabel>
    <relationshipName>Clarity_Form_Connections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection_Field__c/fields/Clarity_Form_Connection__c.field-meta.xml
<CustomField>
    <fullName>forms__Form_Connection__c</fullName>
    <label>Clarity Form Connection</label>
    <referenceTo>forms__Form_Connection__c</referenceTo>
    <relationshipLabel>Clarity Form Connection Fields</relationshipLabel>
    <relationshipName>forms__Form_Connection_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection_Field__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Question</label>
    <referenceTo>Clarity_Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Connection Fields</relationshipLabel>
    <relationshipName>Clarity_Form_Connection_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection_Field__c/fields/Custom_Value__c.field-meta.xml
<CustomField>
    <fullName>Custom_Value__c</fullName>
    <label>Custom Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Lookup__c.field-meta.xml
<CustomField>
    <fullName>Lookup__c</fullName>
    <label>Lookup</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Record_Group__c.field-meta.xml
<CustomField>
    <fullName>Record_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Record Group</label>
    <referenceTo>forms__Form_Question__c</referenceTo>
    <relationshipLabel>Record Groups</relationshipLabel>
    <relationshipName>forms__Form_Questions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MultipleChoice</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Star</fullName>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
            <value>
                <fullName>Ranking</fullName>
            </value>
            <value>
                <fullName>NetPromoterScore</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>RecordGroup</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>ConnectedObject</fullName>
            </value>
            <value>
                <fullName>BOOLEAN</fullName>
            </value>
            <value>
                <fullName>DATETIME</fullName>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
            </value>
            <value>
                <fullName>COMBOBOX</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>ANYTTYPE</fullName>
            </value>
            <value>
                <fullName>BASE64</fullName>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
            </value>
            <value>
                <fullName>INTEGER</fullName>
            </value>
            <value>
                <fullName>LONG</fullName>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
            </value>
            <value>
                <fullName>PERCENT</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OwnerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileService.cls
public with sharing class MobileService {

	
	public static Map<String, Map<String, sObject>> getMobileRecords() {

		Map<String, Map<String, sObject>> records = new Map<String, Map<String, sObject>>(); 

		List<Clarity_Form__c> forms = [SELECT Id FROM Clarity_Form__c WHERE Status__c = 'Published'];

		List<Id> formIds = new List<Id>(); 

		for (Clarity_Form__c form : forms) {
			formIds.add(form.Id); 
		}

		List<Clarity_Form_Connection__c> formConnections = [SELECT Id, Clarity_Form__c, Salesforce_Object__c, New__c, 
		(SELECT Id, Salesforce_Field__c, PreFill__c, Custom_Value__c, Clarity_Form_Question__c FROM Clarity_Form_Connection_Fields__r) 
		FROM Clarity_Form_Connection__c WHERE Clarity_Form__c IN :formIds];


		Map<String, Set<String>> objectFields = new Map<String, Set<String>>(); 

		for(Clarity_Form_Connection__c formConnection : formConnections) {

			for(Clarity_Form_Connection_Field__c field : formConnection.Clarity_Form_Connection_Fields__r) {
							
				if(objectFields.get(formConnection.Salesforce_Object__c) != null) {

					Set<String> fields = objectFields.get(formConnection.Salesforce_Object__c); 
					fields.add(field.Salesforce_Field__c);
					objectFields.put(formConnection.Salesforce_Object__c, fields); 

				} else {

					Set<String> fields = new Set<String>();

					if(formConnection.Salesforce_Object__c == 'Case') {
						fields.add('Subject');
					} else {
						fields.add('Name');
					}

					fields.add('Id');
					fields.add(field.Salesforce_Field__c);
					
					objectFields.put(formConnection.Salesforce_Object__c, fields); 

				}
            }
			
		}

		Integer limitCount = 0;

		for(String objectName : objectFields.keySet()) {

			if(limitCount > 10) {
				continue; 
			}

			List<String> sFields = new List<String>(); 

			Set<String> fields = objectFields.get(objectName); 

			String joinedFields = '';

			for(String field : fields) {
				sFields.add(field);
			}

			if(sFields.size() > 0) {
				joinedFields = String.join(sFields, ', ');
				joinedFields = joinedFields.removeEnd(',');
			} 
			System.debug('joinedFields: ' + joinedFields); 
			String sQuery = 'SELECT ' + joinedFields + ' FROM ' + objectName + ' LIMIT 50';

			List<sObject> results = Database.query(sQuery);

			Map<String, sObject> sObjectRecords = new Map<String, sObject>(); 

			for(SObject result : results) {
				sObjectRecords.put(result.Id, result);
			} 

			records.put(objectName, sObjectRecords);

			limitCount = limitCount + 1; 

		}

		return records;
	}

	public static Map<String, Map<String, List<sObject>>> getMobileForms() {

        Map<String, Map<String, List<sObject>>> formDetails = new Map<String, Map<String, List<sObject>>>(); 

        /**
        * Grab Forms
        **/
        List<Clarity_Form__c> forms = [SELECT Id, Name, Limit__c, Status__c, End_Date__c, Multi_Page__c, Multi_Page_Info__c, Multi_Page_Val__c FROM Clarity_Form__c WHERE Status__c = 'Published'];
		
		if(forms.size() == 0) {
			return formDetails; 
		}

        List<Id> formIds = new List<Id>(); 

        for(Clarity_Form__c form : forms) {
            formIds.add(form.Id); 
        }

        /**
        * Grab Form Questions 
        **/
        Map<Id, List<Clarity_Form_Question__c>> questionsByForms = new Map<Id, List<Clarity_Form_Question__c>>();

        List<Clarity_Form_Question__c> questions = [SELECT Id, Clarity_Form__c, 
            (SELECT Id, Label__c, Active_Flow__c FROM Clarity_Form_Question_Options__r), 
            (SELECT Id, Active__c, Form_Submission__c FROM Clarity_Form_Question_Flow_Designs__r LIMIT 1),
            Title__c, Order__c, Required__c, Lookup__c, Record_Group__c, Type__c FROM Clarity_Form_Question__c WHERE Clarity_Form__c IN :formIds];

        for(Clarity_Form_Question__c question : questions) {
            
            if(questionsByForms.get(question.Clarity_Form__c) != null) {

                questionsByForms.get(question.Clarity_Form__c).add(question); 

            } else {

                questionsByForms.put(question.Clarity_Form__c, new List<Clarity_Form_Question__c>{ question }); 

            }

        }

        /**
        * Grab Form Connections Mapping Fields & Prefilled Fields
        **/

        Map<Id, List<Clarity_Form_Connection_Field__c>> prefillFieldsByForms = new Map<Id, List<Clarity_Form_Connection_Field__c>>();
        Map<Id, List<Clarity_Form_Connection_Field__c>> mappingFieldsByForms = new Map<Id, List<Clarity_Form_Connection_Field__c>>();

        List<Clarity_Form_Connection__c> formConnections = [SELECT Id, Clarity_Form__c, Salesforce_Object__c, New__c, 
            (SELECT Id, Salesforce_Field__c, PreFill__c, Custom_Value__c, Clarity_Form_Question__c FROM Clarity_Form_Connection_Fields__r) 
            FROM Clarity_Form_Connection__c WHERE Clarity_Form__c IN :formIds AND New__c = false];

        for(Clarity_Form_Connection__c formConnection : formConnections) {

            List<Clarity_Form_Connection_Field__c> prefillFields = new List<Clarity_Form_Connection_Field__c>(); 
            List<Clarity_Form_Connection_Field__c> mappingFields = new List<Clarity_Form_Connection_Field__c>(); 

            for(Clarity_Form_Connection_Field__c connectionField : formConnection.Clarity_Form_Connection_Fields__r) {

                if(connectionField.PreFill__c) {

                    prefillFields.add(connectionField);

                } else {

                    mappingFields.add(connectionField);

                }
            }

            if(prefillFieldsByForms.get(formConnection.Clarity_Form__c) != null) {

                prefillFieldsByForms.get(formConnection.Clarity_Form__c).addAll(prefillFields); 

            } else {

                prefillFieldsByForms.put(formConnection.Clarity_Form__c, prefillFields); 

            }

            if(mappingFieldsByForms.get(formConnection.Clarity_Form__c) != null) {

                mappingFieldsByForms.get(formConnection.Clarity_Form__c).addAll(mappingFields); 

            } else {

                mappingFieldsByForms.put(formConnection.Clarity_Form__c, mappingFields); 

            }
        }

        for(Clarity_Form__c form : forms) {

            Map<String, List<sObject>> formDetail = new Map<String, List<sObject>>();
        
            formDetail.put('Form', new List<sObject>{ form });
            formDetail.put('Questions', questionsByForms.get(form.Id));

            //Make grab existing form responses and bring those back?

            formDetail.put('Mapping', mappingFieldsByForms.get(form.Id));
            formDetail.put('Prefills', prefillFieldsByForms.get(form.Id));

            formDetails.put(form.Id, formDetail); 

        }

        return formDetails; 
        
	}

	public static Map<String, Map<String, List<sObject>>> getMobileResponses() {

		Map<String, Map<String, List<sObject>>> responseDetails = new Map<String, Map<String, List<sObject>>>(); 

		List<sObject> records = new  List<sObject>(); 

		List<Clarity_Form_Response__c> responses = [SELECT Id, Clarity_Form__c, Status__c, OwnerId__c FROM Clarity_Form_Response__c];

		Set<Id> responseIds = new Set<Id>();

		for(Clarity_Form_Response__c response : responses) {
			responseIds.add(response.Id); 
		}

		//Answers by responseId
		Map<Id, List<Clarity_Form_Answer__c>> answersByResponseId = new Map<Id, List<Clarity_Form_Answer__c>>();

		List<Clarity_Form_Answer__c> answers = [SELECT Id, Name, Record__c, Answer__c, Date_Answer__c, ContentVersion__c, ContentDocument__c, 
			Clarity_Form_Question__r.Salesforce_Object__c, Clarity_Form_Response__c, Clarity_Form_Question__c, 
			Clarity_Form_Question__r.Record_Group__c, Clarity_Form_Question__r.Type__c  
			FROM Clarity_Form_Answer__c WHERE Clarity_Form_Response__c IN :responseIds];

		for(Clarity_Form_Answer__c answer : answers) {

			if(answersByResponseId.get(answer.Clarity_Form_Response__c) != null) {
				List<Clarity_Form_Answer__c> responseAnswers = answersByResponseId.get(answer.Clarity_Form_Response__c);
				responseAnswers.add(answer); 
				answersByResponseId.put(answer.Clarity_Form_Response__c, responseAnswers);
			} else {
				answersByResponseId.put(answer.Clarity_Form_Response__c, new List<Clarity_Form_Answer__c>{ answer });
			}

		}

		Map<String, Map<String, List<sObject>>> forms = getMobileForms();

		if(forms.size() == 0) {
			return responseDetails;
		}

		for(Clarity_Form_Response__c response : responses) {
			
			Map<String, List<sObject>> formDetail = forms.get(response.Clarity_Form__c);

			List<Clarity_Form_Answer__c> responseAnswers = answersByResponseId.get(response.Id); 

			formDetail.put('Answers', responseAnswers); 
			formDetail.put('Response', new List<Clarity_Form_Response__c>{ response });
			
			responseDetails.put(response.Id, formDetail);

		}

		return responseDetails; 
		
	}

}