mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Criteria__c.object
<CustomObject>
    <label>Clarity Form Question Criteria</label>
    <nameField>
        <label>Clarity Form Question Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Criteria</relationshipLabel>
        <relationshipName>Question_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Option__c.object
<CustomObject>
    <label>Clarity Form Question Option</label>
    <nameField>
        <label>Clarity Form Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Application.cls
public class Application {

	public static final fflib_Application.UnitOfWorkFactory unitOfWork =
		new fflib_Application.UnitOfWorkFactory(
			new List<SObjectType> {
				Form__c.sObjectType,
				Question__c.sObjectType,
				Question_Option__c.sObjectType,
				Response__c.sObjectType,
				Response_Connection__c.sObjectType,
				Answer__c.sObjectType,
				Question_Criteria__c.sObjectType,
				Form_Connection__c.sObjectType,
				Form_Connection_Field__c.sObjectType,
				ContentVersion.sObjectType,
				ContentDocumentLink.sObjectType
			}
		); 

	public static final fflib_Application.ServiceFactory service =
		new fflib_Application.ServiceFactory(
			new Map<Type, Type> {
				IFormsService.class => FormsServiceImpl.class,
				IFormConnectionsService.class => FormConnectionsServiceImpl.class,
				IFormConnectionFieldsService.class => FormConnectionFieldsServiceImpl.class,
				IResponsesService.class => ResponsesServiceImpl.class,
				IQuestionsService.class => QuestionsServiceImpl.class,
				IRecordsService.class => RecordsServiceImpl.class,
				ISyncService.class => SyncServiceImpl.class,
				IResponseConnectionsService.class => ResponseConnectionsServiceImpl.class,
				IAnswersService.class => AnswersServiceImpl.class
			}
		);

	public static final fflib_Application.SelectorFactory selector =
		new fflib_Application.SelectorFactory(
			new Map<SObjectType, Type> {
				Form__c.sObjectType => FormsSelector.class,
				Form_Connection__c.sObjectType => FormConnectionsSelector.class,
				Form_Connection_Field__c.sObjectType => FormConnectionFieldsSelector.class,
				Response__c.sObjectType => ResponsesSelector.class,
				Question__c.sObjectType => QuestionsSelector.class,
				Question_Option__c.sObjectType => QuestionOptionsSelector.class,
				Question_Criteria__c.sObjectType => QuestionCriteriaSelector.class,
				Response_Connection__c.sObjectType => ResponseConnectionsSelector.class,
				Answer__c.sObjecttype => AnswersSelector.class
			}
		);

	public static final fflib_Application.DomainFactory domain =
		new fflib_Application.DomainFactory(
			Application.Selector,
			new Map<SObjectType, Type> {
				Form__c.sObjectType => Forms.Constructor.class,
				Question__c.sObjectType => Questions.Constructor.class,
				Response__c.sObjectType => Responses.Constructor.class,
				Form_Connection__c.sObjectType => FormConnections.Constructor.class,
				ContentVersion.sObjectType => ContentVersions.Constructor.class,
				Answer__c.sObjectType => Answers.Constructor.class
			}
		);
}