mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/restapi/AnswersResource.cls
@RestResource(urlMapping='/v1/Answers/*')
global with sharing class AnswersResource {
	
	@HttpPost
    global static String updateAnswers() {

        RestRequest req = RestContext.request;

		RestResponse res = RestContext.response;
		
		String body = req.requestBody.toString();

		Map<String, String> data = (Map<String, String>)JSON.deserialize(body, Map<String, String>.class);

		String answers = data.get('data');

		List<Answer> parsedAnswers =  (List<Answer>)JSON.deserialize(answers, List<Answer>.class);

		List<Answer__c> readyAnswers = new List<Answer__c>();

		for(Answer parsedAnswer : parsedAnswers) {
			Answer__c answer = new Answer__c(
				UUID__c = parsedAnswer.UUID,
				Answer__c = parsedAnswer.Answer,
				Question__c = parsedAnswer.Question,
				Response__r = new Response__c(UUID__c = parsedAnswer.Response)
			);
			readyAnswers.add(answer); 
		}

		Schema.DescribeFieldResult unique = Answer__c.UUID__c.getDescribe();
		Schema.sObjectField uniqueExternalField = unique.getSObjectField();

		List<Answer__c> savedAnswers = AnswersService.save(readyAnswers, uniqueExternalField);

        return 'Success';

	}

}