mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Result_Holder__c</fullName>
        <label>Result Holder</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Custom_Value__c</fullName>
        <label>Custom Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Process__c.object
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/batchjobs/ConnectionCreateJob.cls
public class ConnectionCreateJob implements Queueable {
  @testVisible
  private static Boolean chainJob = true;

  private Integer order;

  private List<Form_Connection__c> connections;

  private Map<Id, Response_Connection__c> responseConnections;

  private Map<Id, Answer__c> answersByQuestion;

  private Map<Id, Form_Connection_Process__c> processByConnections;

  private Map<String, Id> storedResults;

  private Response__c response;

  public ConnectionCreateJob(
    Integer order,
    List<Form_Connection__c> connections,
    Map<Id, Response_Connection__c> responseConnections,
    Map<Id, Answer__c> answersByQuestion,
    Map<Id, Form_Connection_Process__c> processByConnections,
    Map<String, Id> storedResults,
    Response__c response
  ) {
    this.order = order;
    this.connections = connections;
    this.responseConnections = responseConnections;
    this.answersByQuestion = answersByQuestion;
    this.processByConnections = processByConnections;
    this.storedResults = storedResults;
    this.response = response;
  }

  public void execute(QueueableContext context) {
    Form_Connection__c connection = connections[order];

    Form_Connection_Process__c connectionStatus = processByConnections.get(
      connection.Id
    );

    List<Form_Connection_Field__c> fields = FormConnectionFieldsSelector.newInstance()
      .selectFieldsByConnectionId(connection.Id);

    if (fields.size() > 0) {
      Response_Connection__c rConnection = null;

      if (responseConnections.get(connection.Id) != null) {
        rConnection = responseConnections.get(connection.Id);
      }

      Schema.SObjectType convertType = Schema.getGlobalDescribe()
        .get(connection.Salesforce_Object__c);

      String genericObjectName = convertType.getDescribe().getName();

      Map<String, Schema.SObjectField> sObjectFields = convertType.getDescribe()
        .fields.getMap();

      SObject genericObject = null;
      SObject createdObject = null;

      if (rConnection != null) {
        genericObject = convertType.newSObject(rConnection.Record__c);
      } else {
        genericObject = convertType.newSObject();
      }

      try {
        genericObject = generateSObject(
          genericObject,
          fields,
          sObjectFields,
          answersByQuestion,
          storedResults
        );

        createdObject = ResponsesService.upsertConnectionSObject(
          genericObject,
          connectionStatus,
          response
        );
      } catch (Exception e) {
        System.debug('exception: ' + e.getMessage());
        connectionStatus.Description__c = e.getMessage();
        connectionStatus.Status__c = 'Failed';
        ResponsesService.updateFormConnectionStatus(
          new List<Form_Connection_Process__c>{ connectionStatus }
        );
      }

      if (createdObject != null) {
        storedResults.put(connection.Result_Holder__c, createdObject.Id);
      }
    } else {
      connectionStatus.Description__c = 'No Fields on Connection';
      connectionStatus.Status__c = 'Failed';
      ResponsesService.updateFormConnectionStatus(
        new List<Form_Connection_Process__c>{ connectionStatus }
      );
    }

    if ((connections.size() > (order + 1)) && chainJob) {
      System.enqueueJob(
        new ConnectionCreateJob(
          order + 1,
          connections,
          responseConnections,
          answersByQuestion,
          processByConnections,
          storedResults,
          response
        )
      );
    }

    //Test classes
    if ((connections.size() > (order + 1)) && !chainJob) {
      ConnectionCreateJob job = new ConnectionCreateJob(
        order + 1,
        connections,
        responseConnections,
        answersByQuestion,
        processByConnections,
        storedResults,
        response
      );
      job.execute(null);
    }
  }

  public SObject generateSObject(
    SObject genericObject,
    List<Form_Connection_Field__c> fields,
    Map<String, Schema.SObjectField> sObjectFields,
    Map<Id, Answer__c> answersByQuestion,
    Map<String, Id> storedResults
  ) {
    for (Form_Connection_Field__c field : fields) {
      if (field.Salesforce_Field__c == null)
        continue;

      String dirtyAnswer;
      System.debug('field: ' + field);

      if (
        field.Question__c != null &&
        answersByQuestion.containsKey(field.Question__c)
      ) {
        dirtyAnswer = answersByQuestion.get(field.Question__c).Answer__c != null
          ? answersByQuestion.get(field.Question__c).Answer__c
          : '';
      } else if (field.Custom_Value__c != null) {
        dirtyAnswer = field.Custom_Value__c;

        if (storedResults.get((String) dirtyAnswer) != null) {
          dirtyAnswer = Id.valueOf(storedResults.get((String) dirtyAnswer));
        }
      }

      Schema.DescribeFieldResult fieldResult = sObjectFields.get(
          field.Salesforce_Field__c
        )
        .getDescribe();

      Object cleanAnswer = cleanType(fieldResult, dirtyAnswer);

      genericObject.put(field.Salesforce_Field__c, cleanAnswer);
    }

    return genericObject;
  }

  public Object cleanType(
    Schema.DescribeFieldResult fieldResult,
    String dirtyAnswer
  ) {
    Schema.DisplayType display = fieldResult.getType();

    Object cleanValue = null;

    try {
      if (display == Schema.DisplayType.Boolean) {
        cleanValue = Boolean.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Combobox) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Currency) {
        Decimal c = Decimal.valueOf(dirtyAnswer);
        cleanValue = c.setScale(8, RoundingMode.HALF_EVEN);
      }
      if (display == Schema.DisplayType.Date) {
        cleanValue = Date.parse(dirtyAnswer);
      }
      if (display == Schema.DisplayType.DateTime) {
        cleanValue = Datetime.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Double) {
        cleanValue = Decimal.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Email) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.ID) {
        cleanValue = Id.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Integer) {
        cleanValue = Integer.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Long) {
        cleanValue = Long.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.MultiPicklist) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Percent) {
        cleanValue = Double.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Phone) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Picklist) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Reference) {
        // Schema.SObjectType reference = fieldResult.getReferenceTo();

        // String referenceName = reference.getDescribe().getName();

        cleanValue = Id.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.String) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.TextArea) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
      if (display == Schema.DisplayType.Time) {
        DateTime dt = Datetime.valueOf(dirtyAnswer);
        cleanValue = Time.newInstance(
          dt.hour(),
          dt.minute(),
          dt.second(),
          dt.millisecond()
        );
      }
      if (display == Schema.DisplayType.URL) {
        cleanValue = String.valueOf(dirtyAnswer);
      }
    } catch (Exception e) {
      // add logging of error
    }

    return cleanValue;
  }
}