mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                    <default>true</default>
                    <label>Create</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/FormResponseTest.cls
@isTest
public class FormResponseTest {

    @testSetup
    public static void setup(){

		Form__c form = TestDataFactory.generateForm();

		List<Question__c> questions = TestDataFactory.generateQuestions(new List<Form__c>{ form });

        List<Form_Connection__c> connections = TestDataFactory.generateConnections(false, form,  new List<String>{ 'Opportunity' });

    }

	@isTest
	public static void shouldGetPreview() {

		Form__c form = [SELECT Id FROM Form__c LIMIT 1];

		Test.startTest();

			Map<String, List<sObject>> preview = FormResponse.preview(form.Id); 

		Test.stopTest();

		System.assertEquals(6, preview.size());

	}

	@isTest
	public static void shouldCheckConnections() {

		Form__c form = [SELECT Id FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		List<Form_Connection__c> connections = [SELECT Id FROM Form_Connection__c];

		List<Response_Connection__c> responseConnections = TestDataFactory.generateResponseConnection(response.Id, connections); 

		Test.startTest();

			List<Form_Connection__c> checkConnections = FormResponse.checkConnections(response.Id); 

		Test.stopTest();

		System.assertEquals(0, checkConnections.size());

	}

	@isTest
	public static void shouldGetConnections() {
		
		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		Test.startTest();

			List<Form_Connection__c> connections = FormResponse.getConnections(form.Name); 

		Test.stopTest();

		System.assertEquals(1, connections.size());

	}

	@isTest
	public static void shouldGetRecordGroupResults() {
		
		Form__c form = [SELECT Id FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		List<Question__c> questions = [SELECT Id, Type__c, Title__c FROM Question__c WHERE Type__c = 'RecordGroup' AND Form__c =: form.Id];

        TestDataFactory.generateRecordGroupAnswers(response, questions);

		Test.startTest();

			Map<Id, List<sObject>> recordGroupResults = FormResponse.getRecordGroupResults(response.Id, form.Id); 

		Test.stopTest();

		System.assertNotEquals(1, recordGroupResults.size());

	}

	@isTest
	public static void shouldCreateResponse() {
		
		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		List<Form_Connection__c> connections = [SELECT Id FROM Form_Connection__c];

		Opportunity opp = new Opportunity(Name = 'Test', StageName = 'Prospecting', CloseDate = date.newInstance(2030, 11, 21)); 

		insert opp; 

		List<Map<String, String>> valueConnections = new List<Map<String, String>>(); 

		Map<String, String> mappedConnections = new Map<String, String>();

		mappedConnections.put('key', opp.Id); 
		mappedConnections.put('label', 'Test Connection'); 
		mappedConnections.put('connectionId', connections[0].Id); 
		mappedConnections.put('sObjectName', 'Opportunity'); 
		
		valueConnections.add(mappedConnections);

		Test.startTest();

			Map<String, List<sObject>> create = FormResponse.create(form.Name, JSON.serialize(valueConnections)); 

		Test.stopTest();

		System.assertEquals(1, create.get('Connections').size());
	}

	@isTest
	public static void shouldEditResponse() {
		
		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		Test.startTest();

			Map<String, List<sObject>> edit = FormResponse.edit(response.Id, null);

		Test.stopTest();

		System.assertEquals(new List<Response_Connection__c>(), edit.get('Connections'));

	}

	@isTest
	public static void shouldSaveAnswer() {

		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		List<Question__c> questions = [SELECT Id FROM Question__c];

		List<Answer__c> answers = new List<Answer__c>(); 

		Answer__c answer = new Answer__c(
			Question__c = questions[0].Id, 
			Answer__c				 = 'Test', 
			Response__c = response.Id
		);

		answers.add(answer); 

		String sAnswer = JSON.serialize(answers); 

		Test.startTest();

			List<Answer__c> rAnswers = FormResponse.saveAnswer(sAnswer);

		Test.stopTest();

		System.assertEquals('Test', rAnswers[0].Answer__c);
	}

	@isTest
	public static void shouldSaveResponse() {

		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		List<Question__c> questions = [SELECT Id, Type__c FROM Question__c];

		List<Answer__c> answers = new List<Answer__c>(); 

		Answer__c answer = new Answer__c(
			Question__c = questions[0].Id, 
			Answer__c				 = 'Test',
			Response__c = response.Id
		);

		answers.add(answer); 

		String answerValues = JSON.serialize(answers); 

		String aQuestionId = '';

		for(Question__c question : questions) {
			if(question.Type__c == 'Attachments') {
				aQuestionId = question.Id; 
			}
		}

		List<String> holdAnswers = new List<String>{ '{"' + response.Id + '":{"' + aQuestionId + '":["iVBOR"]}}', answerValues, response.Id }; 

		Test.startTest();

			List<String> save = FormResponse.save(holdAnswers);

		Test.stopTest();

		System.assertEquals(1, save.size());

	}

	@isTest
	public static void shouldSubmitResponse() {

		Form__c form = [SELECT Id, Name FROM Form__c LIMIT 1];

		Response__c response = TestDataFactory.generateResponse(form);

		List<Question__c> questions = [SELECT Id FROM Question__c];

		List<Answer__c> answers = new List<Answer__c>(); 

		Answer__c answer = new Answer__c(
			Question__c = questions[0].Id, 
			Answer__c				 = 'Test',
			Response__c = response.Id
		);

		answers.add(answer); 

		String answerValues = JSON.serialize(answers); 

		List<String> holdAnswers = new List<String>{ '', answerValues, response.Id }; 

		Test.startTest();

			List<String> submit = FormResponse.submit(holdAnswers);

		Test.stopTest();	

		System.assertEquals(1, submit.size());

	}

	@isTest
	public static void shouldReturnLookSearchResults() {
		
		Opportunity opp = new Opportunity(Name = 'Test', StageName = 'Prospecting', CloseDate = date.newInstance(2030, 11, 21)); 
		
		insert opp; 

		List<Id> fixedSearchResults = new List<Id>{opp.Id};
        Test.setFixedSearchResults(fixedSearchResults);

		List<String> searchItems = new List<String>{ 'Tes', 'Opportunity', '' };

		Test.startTest();

			List<FormResponse.LookupResult> search = FormResponse.search(searchItems);

		Test.stopTest();

		System.assertEquals(1, search.size());
	}

}