mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/services/ResponsesServiceImpl.cls
public class ResponsesServiceImpl implements IResponsesService {

	public List<Response__c> getResponses() {
		List<Response__c> responses = ResponsesSelector.newInstance().selectRecent();
		return responses; 
	}

	public List<Response__c> saveResponse(List<Response> responses, Boolean mobile) {
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		
		List<Response__c> newResponses = new List<Response__c>();
		for(Response response : responses) {

			Response__c newResponse = new Response__c(
				Form__c = response.formId,
				UUID__c = response.responseId,
				Status__c = 'Submitted'
			);

			uow.registerNew(newResponse);

			for(Answer answer : response.answers) {
	
				Answer__c newAnswer = new Answer__c(
					Question__c = answer.questionId, 
					Response__c = newResponse.Id,
					Answer__c 	= answer.answer
				);
	
				uow.registerNew(newAnswer, Answer__c.Response__c, newResponse);
	
			}
			newResponses.add(newResponse);			
		}
		uow.commitWork();	
		
		return newResponses; 
		
	}

}