mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Flow_Design__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Clarity Form Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Flow Designs</relationshipLabel>
    <relationshipName>Flow_Designs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                    <default>true</default>
                    <label>Create</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Criteria__c.object
<CustomObject>
    <label>Clarity Form Question Criteria</label>
    <nameField>
        <label>Clarity Form Question Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clarity_Form_Question_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Criteria</relationshipLabel>
        <relationshipName>Question_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Option__c.object
<CustomObject>
    <label>Clarity Form Question Option</label>
    <nameField>
        <label>Clarity Form Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Choice_Image__c</fullName>
        <label>Choice Image</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Clarity_Form_Question_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MultipleChoice</fullName>
    </customValue>
    <customValue>
        <fullName>Comment</fullName>
    </customValue>
    <customValue>
        <fullName>Star</fullName>
    </customValue>
    <customValue>
        <fullName>Dropdown</fullName>
    </customValue>
    <customValue>
        <fullName>Ranking</fullName>
    </customValue>
    <customValue>
        <fullName>NetPromoterScore</fullName>
    </customValue>
    <customValue>
        <fullName>Slider</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Lookup</fullName>
    </customValue>
    <customValue>
        <fullName>RecordGroup</fullName>
    </customValue>
    <customValue>
        <fullName>Image</fullName>
    </customValue>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Attachments</fullName>
    </customValue>
    <customValue>
        <fullName>ConnectedObject</fullName>
    </customValue>
    <description>Question Types Currently Available</description>
    <masterLabel>Clarity Form Question Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/builders/FormResponse.cls
global with sharing class FormResponse {

    private final static Integer MAX_RESULTS = 5;
    
    @RemoteAction
    global static Map<String, List<sObject>> preview(String formId) {

        Map<String, List<sObject>> formDetails = FormService.create((Id)formId);

        return formDetails; 

    }

    @RemoteAction 
    global static List<Form_Connection__c> checkConnections(String responseId) {
        
        List<Form_Connection__c> requiredConnections = new List<Form_Connection__c>(); 

        Response__c response = [SELECT Id, Form__c FROM Response__c WHERE Id =: responseId LIMIT 1];

        Map<Id, Form_Connection__c> connections = new Map<Id, Form_Connection__c>([SELECT Id, Salesforce_Object__c, New__c FROM Form_Connection__c WHERE Form__c =: response.Form__c AND New__c = false]);

        if(connections.size() > 0) {

            List<Response_Connection__c> responseConnections = [SELECT Id, Form_Connection__c 
                FROM Response_Connection__c WHERE Response__c =: responseId AND Form_Connection__c IN :connections.keySet()];

            if(responseConnections.size() == 0) {
                return connections.values();
            } 

            Set<Id> responseConnectedIds = new Set<Id>(); 

            for(Response_Connection__c rc : responseConnections){
                responseConnectedIds.add(rc.Form_Connection__c); 
            }
			System.debug('responseConnectedIds: ' + responseConnectedIds); 
            for(Form_Connection__c connection : connections.values()) {
                if(!responseConnectedIds.contains(connection.Id)) {
                    requiredConnections.add(connection); 
                }
            }

        }

        return requiredConnections;
    }

    @RemoteAction
    global static List<Form_Connection__c> getConnections(String formName) {

        Form__c form = [SELECT Id FROM Form__c WHERE Name =: formName LIMIT 1];

        List<Form_Connection__c> connections = [SELECT Id, Salesforce_Object__c, New__c FROM Form_Connection__c WHERE Form__c =: form.Id];

        return connections; 

    }

    @RemoteAction
    global static Map<Id, List<sObject>> getRecordGroupResults(String responseId, String formId) {

        List<Question__c> questions = [SELECT Id, 
            (SELECT Id, Label__c, Active_Flow__c, Choice_Image__c, Order__c FROM Question_Options__r), 
            (SELECT Id, Active__c, Form_Submission__c FROM Flow_Designs__r LIMIT 1),
            (SELECT Id, Field_Type__c, Field__c, Operator__c, Type__c, Value__c, Question__c FROM Question_Criteria__r),
            Salesforce_Object__c, FreeText_Type__c, Title__c, Order__c, Required__c, Lookup__c, 
            Salesforce_Field__c, Record_Group__c, Record_Group__r.Salesforce_Object__c, 
            Page__c, Type__c FROM Question__c WHERE Form__c =: formId];

        List<Answer__c> answers = [SELECT Id, Record__c, Answer__c, Date_Answer__c, ContentDocument__c, 
            Question__r.Salesforce_Object__c, Response__c, Question__c, 
            Question__r.Record_Group__c, Question__r.Type__c  
            FROM Answer__c WHERE Response__c =: responseId];

        Map<Id, List<sObject>> records = FormService.getRecordGroupSubmissions(answers, questions);

        return records; 

    }

    @RemoteAction
    global static Map<String, List<sObject>> create(String formName, String sConnections) {

        Map<String, List<sObject>> formDetails = FormService.create(formName, sConnections);

        return formDetails; 

    }

    @RemoteAction
    global static Map<String, List<sObject>> edit(String responseId, String sConnections) {

        Map<String, List<sObject>> formDetails = FormService.edit(responseId, sConnections);

        return formDetails; 

    }

    @RemoteAction
    global static List<Answer__c> saveAnswer(String answers){

        List<Answer__c> savedAnswers = FormService.save(answers); 

        return savedAnswers;
        
    }

    @RemoteAction
    global static List<String> save(List<String> answerValues) {

        String answerImages = answerValues[0];
        String answers = answerValues[1];
        String formResponseId = answerValues[2]; 

        List<Answer__c> savedAnswerImages = FormService.upload(answerImages); 

        List<Answer__c> savedAnswers = FormService.save(answers); 

        List<String> success = FormService.updateStatus(new List<String>{ formResponseId }, 'In Progress');

        return success; 

    }

    @RemoteAction
    global static List<String> submit(List<String> answerValues) {

        String answerImages = answerValues[0];
        String answers = answerValues[1];
        String formResponseId = answerValues[2]; 

        List<Answer__c> savedAnswerImages = FormService.upload(answerImages); 

        List<Answer__c> savedAnswers = FormService.save(answers); 

        List<String> success = FormService.updateStatus(new List<String>{ formResponseId }, 'Submitted');

        return success; 
        
    }
	
    @RemoteAction 
    global static List<LookupResult> search(List<String> searchItems) {

        String searchTerm = searchItems[0];
        String lookupObject = searchItems[1];
        String questionId = searchItems[2]; 

        searchTerm += '*';

		String returningField = 'Name';

		if(lookupObject == 'Case') {
			returningField = 'Subject';
		}

		Schema.SObjectType convertType = Schema.getGlobalDescribe().get(lookupObject);

		List<LookupResult> results = new List<LookupResult>();

		Boolean access = convertType.getDescribe().isAccessible();

		if(access) {

			String searchString = 'FIND ' + '\'%' + searchTerm + '%\'' + ' IN ALL FIELDS RETURNING ' + lookupObject + ' (Id, ' + returningField + ')';

			List<List<sObject>> searchResults = search.query(searchString);


			List<sObject> records = ((List<sObject>) searchResults[0]);

			for (sObject record : records) {
				results.add(new LookupResult(record.Id, lookupObject, (String)record.get(returningField), lookupObject));
			}

		}

        return results;
    }

    @RemoteAction 
    global static sObject createRecord(List<String> recordValues) {

        String responseId = recordValues[0]; 
        String recordGroupId = recordValues[1]; 
        String sObjectName = recordValues[2];
        String records = recordValues[3];

        Schema.SObjectType convertType = Schema.getGlobalDescribe().get(sObjectName);

        List<Record> recordFields = (List<Record>)JSON.deserialize(records, List<Record>.class);

        sObject genericObject = convertType.newSObject();

        Map<String, Schema.SObjectField> sObjectFields = convertType.getDescribe().fields.getMap();

        for(Record record : recordFields) {

			Boolean accessField = sObjectFields.get(record.field).getDescribe().isCreateable();

			if(accessField) {

				if(record.type == 'Date') {

					Date value = Date.valueOf(record.value);
					genericObject.put(record.field, value);

				} else {
					
					genericObject.put(record.field, record.value);

				}

			}

        }

		Boolean access = convertType.getDescribe().isCreateable(); 

		if(access) {
        
			Database.UpsertResult result = Database.upsert(genericObject, true); 

			if(!result.isSuccess()) {

				System.debug('error: ' + result.getErrors());

			}

			Answer__c answer = new Answer__c(
				Response__c = responseId, 
				Question__c = recordGroupId,
				Record__c                = result.getId()
			);

			Database.UpsertResult resultAnswer = Database.upsert(answer, true); 

			if(!resultAnswer.isSuccess()) {

				System.debug('error: ' + resultAnswer.getErrors());

			}

		} else {

			System.debug('User lacks create access to this object.');

		}
		
		return genericObject;

    }

    @RemoteAction
    global static Map<String, Map<String, Map<String, String>>> getRecordGroupPicklist(List<String> sPicklistQuestionIds) {

        List<Question__c> picklistQuestions = [SELECT Id, Title__c, Order__c, Required__c, Lookup__c, Record_Group__c, 
            Record_Group__r.Salesforce_Object__c, Salesforce_Field__c, Type__c FROM Question__c WHERE ID IN :sPicklistQuestionIds];

        Map<String, List<String>> rcp = FormService.filterRecordGroupPicklist(picklistQuestions);

        Map<String, Map<String, Map<String, String>>> values = FormService.getSalesforcePicklistValues(rcp);

        return values; 

    }

    global class Record {

        public String field; 
        public String value; 
        public String type; 

    }

    global class LookupResult {

        private Id id;
        private String type;
        private String label;
        private String subTitle;

        public LookupResult(Id id, String type, String label, String subTitle) {
            this.id = id;
            this.type = type;
            this.label = label;
            this.subTitle = subTitle;
        }

    }
    
}