mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContentDocument__c</fullName>
        <label>ContentDocument</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentVersion__c</fullName>
        <label>ContentVersion</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Answer_UUID__c</fullName>
        <label>Answer UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/domains/ContentVersionUnitofWorkHelper.cls
public class ContentVersionUnitofWorkHelper implements fflib_SObjectUnitOfWork.IDoWork
{       
    public Database.UpsertResult[] AnswerResults {get; private set;}
	public Database.UpsertResult[] ContentDocumentLinkResults {get; private set;}

	private List<ContentVersion> cv_records;

    public ContentVersionUnitofWorkHelper()
    {  
        cv_records = new List<ContentVersion>();
    }
     
    public void registerContentVersions(List<ContentVersion> records)
    {
		cv_records.addAll(records);
    }
     
    public void doWork()
    {
		Set<Id> cv_recordIds = new Set<Id>();

		for(ContentVersion cv : cv_records) {
			cv_recordIds.add(cv.Id); 
		}
		
		List<Answer__c> answers = new List<Answer__c>();
		List<ContentDocumentLink> links = new List<ContentDocumentLink>();

		List<ContentVersion> updatedCVRecords = ContentVersionsSelector.newInstance().selectById(cv_recordIds);

		for(ContentVersion cv : updatedCVRecords) {

			Answer__c answer = new Answer__c(
				UUID__c = cv.Answer_UUID__c,
				ContentDocument__c = cv.ContentDocumentId,
				ContentVersion__c = cv.Id,
				Question__c = cv.Question__c,
				Response__c = cv.Response__c
			);
			
			answers.add(answer); 

			ContentDocumentLink formLink = new ContentDocumentLink(
				ContentDocumentId   = cv.ContentDocumentId, //Add ContentDocumentId
				LinkedEntityId      = cv.Response__c, //Add attachment parentId
				ShareType           = 'V', //V - Viewer permission. C - Collaborator permission. I - Inferred permission.
				Visibility          = 'AllUsers' //AllUsers, InternalUsers, SharedUsers
			);

			links.add(formLink); 

		}

		AnswerResults = Database.upsert(answers, false);  
		
		for(Answer__c answer : answers) {

			ContentDocumentLink answerLink = new ContentDocumentLink(
                ContentDocumentId   = answer.ContentDocument__c, //Add ContentDocumentId
                LinkedEntityId      = answer.Id, //Add attachment parentId
                ShareType           = 'V', //V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                Visibility          = 'AllUsers' //AllUsers, InternalUsers, SharedUsers
			);
			
			links.add(answerLink); 

		}

		ContentDocumentLinkResults = Database.upsert(links, false);                
    }
}