mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                    <default>true</default>
                    <label>Create</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Process__c.object
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesforce_Connection_Object__c</fullName>
        <label>Salesforce Connection Object</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/classes/ConnectionCreateJobTest.cls
@isTest
public class ConnectionCreateJobTest {

	public static void generateConnectedResponseForm(Form__c form, List<Question__c> questions, List<String> newConnections, List<Map<String, Id>> connectionFields, List<Map<String, String>> customConnectionFields, Boolean withAnswers) {

		List<Form_Connection__c> connections = TestDataFactory.generateConnections(true, form.Id, newConnections);

		List<Form_Connection__c> connectionsSaved = FormConnectionsService.save(new List<Form_Connection__c>(), connections);

		List<Form_Connection_Field__c> allFields = new List<Form_Connection_Field__c>();
		
		Integer connectionFieldCount = 0;

		for(Map<String, String> connectionField : connectionFields) {

			Form_Connection__c connection = connections[connectionFieldCount];
			List<Form_Connection_Field__c> fields = TestDataFactory.generateConnectionFields(connection.Id, connectionField);
			List<Form_Connection_Field__c> fieldsSaved = FormConnectionFieldsService.updateFields(fields, connection.Id);
			connectionFieldCount++; 

		}

		Integer customConnectionFieldCount = 0;

		for(Map<String, String> customConnectionField : customConnectionFields) {

			Form_Connection__c connection = connections[customConnectionFieldCount];
			List<Form_Connection_Field__c> customFields = TestDataFactory.generateCustomConnectionFields(connection.Id, customConnectionField);
			List<Form_Connection_Field__c> customFieldsSaved = FormConnectionFieldsService.updateFields(customFields, connection.Id);
			customConnectionFieldCount++; 
			
		}

		form.Status__c = 'Published';

		Form__c updatedForm = FormsService.updateForm(form);

		Response__c response = ResponsesService.create(updatedForm.Id); 

		if(withAnswers) {

			Map<String,String> answers = TestDataFactory.generateAnswers(response, questions);

			List<Answer__c> answersList = new List<Answer__c>(); 

			for(String questionId : answers.keySet()) {
				Answer__c answer = new Answer__c(
					Question__c = questionId,
					Answer__c = answers.get(questionId),
					Response__c = response.Id
				);
				answersList.add(answer);
			}

			Response__c updatedResponse = ResponsesService.save(answersList, response.Id, response.Status__c); 

		}

	}

    @testSetup
    public static void setup(){
						
		User user = TestDataFactory.generateUserWithBuilderPermissions(); 

		System.runAs(user) {

			List<Form__c> forms = TestDataFactory.generateForms(5);

			List<Question__c> questions = TestDataFactory.generateQuestions(forms);
			
			List<Question__c> savedQuestions = QuestionsService.saveQuestions(questions);

			//response 1 
			List<Map<String, String>> fields0 = new List<Map<String, Id>>();
			fields0.add(new Map<String, String>{'ForecastCategoryName' =>  questions[0].Id });
			generateConnectedResponseForm(forms[0], savedQuestions, new List<String>{ 'Opportunity' }, fields0, new List<Map<String, String>>(), false);

			//response 2
			List<Map<String, String>> customFields = new List<Map<String, String>>();
			customFields.add(new Map<String, String>{ 'Name' => 'Custom Name', 'StageName' => 'Prospecting', 'CloseDate' => '07/22/2030' });
			generateConnectedResponseForm(forms[1], savedQuestions, new List<String>{ 'Opportunity' }, new List<Map<String, Id>>(), customFields, true);
			
			//response 3
			List<Map<String, String>> customFields1 = new List<Map<String, String>>();
			customFields1.add(new Map<String, String>{ 'Name' => 'Custom Name' });
			customFields1.add(new Map<String, String>{ 'Name' => 'Clarity' });
			generateConnectedResponseForm(forms[2], savedQuestions, new List<String>{ 'Account', 'Account' }, new List<Map<String, Id>>(), customFields1, true);

			//response 4
			List<Question__c> commentQuestions1 = [SELECT Id, Type__c, Title__c FROM Question__c WHERE Type__c = 'Comment' AND Form__c =: forms[3].Id];
			List<Map<String, String>> fields3 = new List<Map<String, Id>>();
			fields3.add(new Map<String, String>{ 'Name' => commentQuestions1[0].Id });
			generateConnectedResponseForm(forms[3], questions, new List<String>{ 'Account' }, fields3, new List<Map<String, String>>(), true);

			//response 5 prep
			List<Question__c> commentQuestions2 = [SELECT Id,  Type__c, Title__c FROM Question__c WHERE Type__c = 'Comment' AND Form__c =: forms[4].Id];

			List<Map<String, String>> customFields3 = new List<Map<String, String>>();
			customFields3.add(new Map<String, String>{ 'Name' => 'Custom Parent Name' });
			customFields3.add(new Map<String, String>{ 'Name' => 'Custom Child Name', 'ParentId' => '{Connection_Account}' });

			generateConnectedResponseForm(forms[4], commentQuestions2, new List<String>{ 'Account', 'Account' }, new List<Map<String, String>>(), customFields3, true);
	
		}
	}

    @isTest
    public static void shouldUpdateProcessToFailed() {

		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];
		
		System.runAs(user) {
        
			ConnectionCreateJob.chainJob = false;

			List<Response__c> responses = [SELECT Id, Name, Status__c, Form__c FROM Response__c];

			Test.startTest();       

				//can skip controller to test service and process directly
				Response__c response = ResponsesService.save(new List<Answer__c>(), responses[0].Id, 'Submitted'); 
			
			Test.stopTest(); 

			List<Opportunity> opportunities = [SELECT Id, ForecastCategoryName FROM Opportunity];

			List<Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Form_Connection_Process__c WHERE Response__c =: response.Id]; 

			for(Form_Connection_Process__c process : connectionProcess) {
				System.assertEquals('Failed', process.Status__c); 
			}

			System.assertEquals(0, opportunities.size());
			
		}

	}
	
	/**
	 * Fail to create opportunity because missing Opportunity__c on Response__c
	 */

    @isTest
    public static void shouldFailToCreateOpportunityConnectionFromCustomValue() {

		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];
		
		System.runAs(user) {

			ConnectionCreateJob.chainJob = false;

			List<Response__c> responses = [SELECT Id, Form__c, Status__c FROM Response__c];

			Test.startTest();       
				
				Response__c response = ResponsesService.save(new List<Answer__c>(), responses[1].Id, 'Submitted'); 
			
			Test.stopTest(); 

			List<Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Form_Connection_Process__c]; 

			for(Form_Connection_Process__c process : connectionProcess) {
				System.assertEquals('Success', process.Status__c); 
			}

			List<Opportunity> opportunities = [SELECT Id FROM Opportunity];

			System.assertEquals(1, opportunities.size());
			
		}
    }

    @isTest
    public static void shouldCreateMultipleConnectionsFromCustomValues(){

		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];
		
		System.runAs(user) {

			ConnectionCreateJob.chainJob = false;

			List<Response__c> responses = [SELECT Id, Status__c FROM Response__c];

			Test.startTest();       
				
				Response__c response = ResponsesService.save(new List<Answer__c>(), responses[2].Id, 'Submitted'); 
			
			Test.stopTest(); 

			List<Account> accounts = [SELECT Id FROM Account];

			System.assertEquals(2, accounts.size());
			
			List<Form_Connection_Process__c> connectionProcess = [SELECT Id, Status__c FROM Form_Connection_Process__c]; 

			for(Form_Connection_Process__c process : connectionProcess) {
				System.assertEquals('Success', process.Status__c); 
			}
			
		}
    }

    @isTest
    public static void shouldCreateAccountConnectionFromQuestionValue() {

		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];
		
		System.runAs(user) {

			ConnectionCreateJob.chainJob = false;

			List<Response__c> responses = [SELECT Id, Status__c, Form__c FROM Response__c];

			Test.startTest();       
			
				Response__c response = ResponsesService.save(new List<Answer__c>(), responses[3].Id, 'Submitted'); 
			
			Test.stopTest(); 

			List<Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Form_Connection_Process__c WHERE Response__c =: response.Id]; 

			for(Form_Connection_Process__c process : connectionProcess) {
				System.assertEquals('Success', process.Status__c); 
			}

			List<Account> accounts = [SELECT Id, Name FROM Account];

			System.assertEquals(1, accounts.size());
			
		}

    }

    @isTest
    public static void shouldCreateMultipleConnectionsWithAppropriateStoreIds(){

		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];
		
		System.runAs(user) {
			ConnectionCreateJob.chainJob = false;

			List<Response__c> responses = [SELECT Id, Status__c, Form__c FROM Response__c];

			Test.startTest();       
				
				Response__c response = ResponsesService.save(new List<Answer__c>(), responses[4].Id, 'Submitted'); 
			
			Test.stopTest(); 

			List<Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Form_Connection_Process__c WHERE Response__c =: response.Id]; 

			for(Form_Connection_Process__c process : connectionProcess) {
				System.assertEquals('Success', process.Status__c); 
			}

			List<Account> accounts = [SELECT Id, ParentId FROM Account];

			System.assertEquals(accounts.size(), 2);

			System.assertEquals(accounts[0].Id, accounts[1].ParentId);
		}

    }

}