mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Answer_UUID__c</fullName>
        <label>Answer UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/restapi/AttachmentsResource.cls
@RestResource(urlMapping='/v1/Attachments/*')
global with sharing class AttachmentsResource {
  @HttpPost
  global static List<Answer__c> updateAttachments() {
    RestRequest req = RestContext.request;

    RestResponse res = RestContext.response;

    String body = req.requestBody.toString();

    Map<String, String> data = (Map<String, String>) JSON.deserialize(
      body,
      Map<String, String>.class
    );

    String attachments = data.get('data');

    List<Attachment> parsedAttachments = (List<Attachment>) JSON.deserialize(
      attachments,
      List<Attachment>.class
    );

    List<ContentVersion> cvs = new List<ContentVersion>();

    List<String> answerIds = new List<String>();

    for (Attachment attachment : parsedAttachments) {
      ContentVersion content = new ContentVersion(
        ContentLocation = 'S',
        PathOnClient = attachment.Name,
        Origin = 'H',
        Title = attachment.Name,
        Response__r = new Response__c(UUID__c = attachment.Response),
        Answer_UUID__c = attachment.UUID,
        Question__c = attachment.Question,
        VersionData = EncodingUtil.base64Decode(attachment.Base64) // converting your binary string to Blob
      );

      answerIds.add(attachment.UUID);

      cvs.add(content);
    }

    List<Answer__c> answers = AnswersService.save(cvs, answerIds);

    return answers;
  }
}