mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>35</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/services/AnswersServiceImpl.cls
public class AnswersServiceImpl implements IAnswersService {
  public List<Answer__c> save(List<Answer__c> parsedAnswers) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    uow.registerUpsert(parsedAnswers);

    uow.commitWork();

    return parsedAnswers;
  }

  public List<Answer__c> save(
    List<Answer__c> parsedAnswers,
    Schema.sObjectField uniqueExternalField
  ) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    uow.registerUpsert(parsedAnswers, uniqueExternalField);

    uow.commitWork();

    return parsedAnswers;
  }

  public List<Answer__c> save(
    List<ContentVersion> attachments,
    String questionId,
    String responseId
  ) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    IContentVersions cvs = ContentVersions.newInstance(attachments);

    cvs.save(uow);

    uow.commitWork();

    List<Answer__c> answers = AnswersSelector.newInstance()
      .selectByCustomQuery(
        'Response__c = :responseId AND Question__c = :questionId',
        questionId,
        responseId
      );

    return answers;
  }

  public List<Answer__c> save(
    List<ContentVersion> attachments,
    List<String> answerIds
  ) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    IContentVersions cvs = ContentVersions.newInstance(attachments);

    cvs.save(uow);

    uow.commitWork();

    List<Answer__c> answers = AnswersSelector.newInstance()
      .selectByCustomQuery('UUID__c IN :answerIds', answerIds);

    return answers;
  }
}