mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContentDocument__c</fullName>
        <label>ContentDocument</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentVersion__c</fullName>
        <label>ContentVersion</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/domains/ContentVersions.cls
public with sharing class ContentVersions extends fflib_SObjectDomain implements IContentVersions {

	public void save(fflib_ISObjectUnitOfWork uow)
	{

		uow.registerNew((List<ContentVersion>) Records);
		
		for(ContentVersion cv : (List<ContentVersion>) Records) {
	
			Answer__c answer = new Answer__c(
				ContentDocument__c = cv.ContentDocumentId,
				ContentVersion__c = cv.Id,
				Question__c = cv.Question__c,
				Response__c = cv.Response__c
			);

			uow.registerNew(answer, Answer__c.ContentVersion__c, cv);				

			ContentDocumentLink formLink = new ContentDocumentLink(
				ContentDocumentId   = cv.ContentDocumentId, //Add ContentDocumentId
				LinkedEntityId      = cv.Response__c, //Add attachment parentId
				ShareType           = 'V', //V - Viewer permission. C - Collaborator permission. I - Inferred permission.
				Visibility          = 'AllUsers' //AllUsers, InternalUsers, SharedUsers
			);

			uow.registerNew(formLink, ContentDocumentLink.ContentDocumentId, cv);				

            ContentDocumentLink answerLink = new ContentDocumentLink(
                ContentDocumentId   = cv.ContentDocumentId, //Add ContentDocumentId
                LinkedEntityId      = answer.Id, //Add attachment parentId
                ShareType           = 'V', //V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                Visibility          = 'AllUsers' //AllUsers, InternalUsers, SharedUsers
            );
        
			uow.registerNew(answerLink, ContentDocumentLink.LinkedEntityId, answer);				

		}

	}

	public static IContentVersions newInstance(List<ContentVersion> recordList)
	{
		return (IContentVersions) Application.Domain.newInstance(recordList);
	}

	public static IContentVersions newInstance(Set<Id> recordIdSet)
	{
		return (IContentVersions) Application.Domain.newInstance(recordIdSet);
	}
	
	public ContentVersions(List<ContentVersion> sObjectList)
	{
		// Domain classes are initialised with lists to enforce bulkification throughout
		super(sObjectList);
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new ContentVersions(sObjectList);
		}
	}
	
}