mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Process__c.object
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/services/ResponsesService.cls
public with sharing class ResponsesService {
  public static List<Response__c> getResponses() {
    return service().getResponses();
  }

  public static List<Response__c> getResponsesByOwner(List<String> users) {
    return service().getResponsesByOwner(users);
  }

  public static Response__c getResponseWithDetailsById(String responseId) {
    return service().getResponseWithDetailsById(responseId);
  }

  public static List<Response__c> getResponsesByFormVersionId(
    String responseId
  ) {
    return service().getResponsesByFormVersionId(responseId);
  }

  public static List<Response__c> getResponsesByConnectedId(String recordId) {
    return service().getResponsesByConnectedId(recordId);
  }

  public static Response__c getResponseById(String responseId) {
    return service().getResponseById(responseId);
  }

  public static Response__c create(String formVersionId) {
    return service().create(formVersionId);
  }

  public static Response__c create(
    String formVersionId,
    Map<String, String> connectionRecordIds
  ) {
    return service().create(formVersionId, connectionRecordIds);
  }

  public static Response__c save(
    List<Answer__c> answers,
    String responseId,
    String status
  ) {
    return service().save(answers, responseId, status);
  }

  public static List<Response__c> save(
    List<Response__c> responses,
    Schema.sObjectField uniqueExternalField
  ) {
    return service().save(responses, uniqueExternalField);
  }

  public static List<Response_Connection__c> saveConnections(
    String responseId,
    List<Map<String, String>> connections
  ) {
    return service().saveConnections(responseId, connections);
  }

  public static Id deleteById(String responseId) {
    return service().deleteById(responseId);
  }

  public static List<String> deleteResponsesByUUIDs(List<String> UUIDs) {
    return service().deleteResponsesByUUIDs(UUIDs);
  }

  public static Map<String, List<Map<String, String>>> getResultAnswersByFormVersionId(
    String recordId,
    Integer offset
  ) {
    return service().getResultAnswersByFormVersionId(recordId, offset);
  }

  public static sObject upsertConnectionSObject(
    sObject record,
    Form_Connection_Process__c connectionStatus,
    Response__c response
  ) {
    return service()
      .upsertConnectionSObject(record, connectionStatus, response);
  }

  public static void updateFormConnectionStatus(
    List<Form_Connection_Process__c> connectionStatus
  ) {
    service().updateFormConnectionStatus(connectionStatus);
  }

  public static IResponsesService service() {
    return (IResponsesService) Application.service.newInstance(
      IResponsesService.class
    );
  }
}