mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/fields/Clarity_Form_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Assignment</label>
    <referenceTo>Clarity_Form_Assignment__c</referenceTo>
    <relationshipLabel>Clarity Forms</relationshipLabel>
    <relationshipName>Clarity_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/Clarity_Form_Answer__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <label>Clarity Form Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Question</label>
    <referenceTo>Clarity_Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Response__c</fullName>
    <label>Clarity Form Response</label>
    <referenceTo>Clarity_Form_Response__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment__c/Clarity_Form_Assignment__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Assignment</label>
    <nameField>
        <label>Clarity Form Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Assignment__c/fields/Assign__c.field-meta.xml
<CustomField>
    <fullName>Assign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>forms__Form_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment__c/fields/Default_Assign__c.field-meta.xml
<CustomField>
    <fullName>Default_Assign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Assign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>forms__Form_Assignments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <defaultValue>&quot;AND&quot;</defaultValue>
    <label>Logic</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment_Rule__c/Clarity_Form_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Assignment Rule</label>
    <nameField>
        <label>Clarity Form Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Assignment_Rule__c/fields/Clarity_Form_Assignment__c.field-meta.xml
<CustomField>
    <fullName>forms__Form_Assignment__c</fullName>
    <label>Clarity Form Assignment</label>
    <referenceTo>forms__Form_Assignment__c</referenceTo>
    <relationshipLabel>Clarity Form Assignment Rules</relationshipLabel>
    <relationshipName>forms__Form_Assignment_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment_Rule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not Equal</fullName>
            </value>
            <value>
                <fullName>Is Null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <defaultValue>&quot;ALL&quot;</defaultValue>
    <label>Logic</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OwnerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FormResponseAssignment.cls
/**
* @author efigenio.ben@clarityforms.io
* @company Clarity Forms
* @date 07/19/2019
*
* @group Clarity_Form_Response__c
*
* @description On update or insert of Clarity_Form_Response__c, assign to Assigned user
*/
public class FormResponseAssignment {

    private static Map<Id, Clarity_Form_Assignment__c> Assignment {
        get {

            if(Assignment == null) {

                Assignment = new Map<Id, Clarity_Form_Assignment__c>();

                Map<Id, Id> formIdByAssignmentIds = new Map<Id, Id>(); 

                List<Id> formIds = new List<Id>();

                for(Clarity_Form_Response__c response : (List<Clarity_Form_Response__c>)Trigger.new) {
                    formIds.add(response.Clarity_Form__c);
                }

                List<Clarity_Form__c> forms = [SELECT Id, Clarity_Form_Assignment__c FROM Clarity_Form__c WHERE Id IN :formIds AND Clarity_Form_Assignment__c != ''];

                for(Clarity_Form__c form : forms) { 

                    formIdByAssignmentIds.put(form.Clarity_Form_Assignment__c, form.Id);

                }

                List<Clarity_Form_Assignment__c> assignments = [SELECT Id, Logic__c, Assign__c, (SELECT Id, Operator__c, Field__c, Value__c FROM Clarity_Form_Assignment_Rules__r) FROM Clarity_Form_Assignment__c WHERE Id IN :formIdByAssignmentIds.keySet()];

                for(Clarity_Form_Assignment__c a : assignments) {
                    Id formId = formIdByAssignmentIds.get(a.Id); 
                    Assignment.put(formId, a);
                }

            }
            return Assignment;
        }
        set; 
    }

    private static Map<Id, Map<Id, Clarity_Form_Answer__c>> ResponseAnswers {
        get {
            if(ResponseAnswers == null) {

                ResponseAnswers = new Map<Id, Map<Id, Clarity_Form_Answer__c>>(); 

                List<Clarity_Form_Answer__c> answers = [SELECT Id, Clarity_Form_Question__c, Clarity_Form_Response__c, Answer__c FROM Clarity_Form_Answer__c WHERE Clarity_Form_Response__c IN :Trigger.newMap.keySet()];

                for(Clarity_Form_Answer__c answer : answers) {

                    Map<Id, Clarity_Form_Answer__c> currentResponseAnswers = new Map<Id, Clarity_Form_Answer__c>(); 

                    if(ResponseAnswers.get(answer.Clarity_Form_Response__c) != null) {
                        
                        currentResponseAnswers = ResponseAnswers.get(answer.Clarity_Form_Response__c); 

                    } else {

                        currentResponseAnswers = new Map<Id, Clarity_Form_Answer__c>(); 

                    }

                    currentResponseAnswers.put(answer.Clarity_Form_Question__c, answer);

                    ResponseAnswers.put(answer.Clarity_Form_Response__c, currentResponseAnswers);
                }

            }
            return ResponseAnswers;
        }
        set; 
    }

    public static void execute(Clarity_Form_Response__c oldResponse, Clarity_Form_Response__c response) {
        
        if(oldResponse.Status__c == 'Submitted' || response.Status__c != 'Submitted') return; 
                
        if(Assignment.get(response.Clarity_Form__c) == null) return; 

        Clarity_Form_Assignment__c assignment = Assignment.get(response.Clarity_Form__c); 

        if(assignment.Assign__c == null && assignment.Default_Assign__c == null) return;

        if(assignment.Clarity_Form_Assignment_Rules__r.size () == 0) {
            response.OwnerId__c = assignment.Assign__c;
            return;
        } 

        List<Clarity_Form_Assignment_Rule__c> rules = assignment.Clarity_Form_Assignment_Rules__r;

        Boolean shouldAssign = false; 

        Map<Id, Clarity_Form_Answer__c> questionAnswers = ResponseAnswers.get(response.Id);

        if(assignment.Logic__c == 'OR') {

            for(Clarity_Form_Assignment_Rule__c rule : rules) {
                
                if(questionAnswers.get(rule.Field__c) != null) {

                    Clarity_Form_Answer__c answer = questionAnswers.get(rule.Field__c); 

                    shouldAssign = operateOnAnswer(answer.Answer__c, rule); 

                    if(shouldAssign) {
                        break; 
                    }

                }

            }

        }

        if(assignment.Logic__c == 'AND') {

            for(Clarity_Form_Assignment_Rule__c rule : rules) {
                
                if(questionAnswers.get(rule.Field__c) != null) {

                    Clarity_Form_Answer__c answer = questionAnswers.get(rule.Field__c); 

                    shouldAssign = operateOnAnswer(answer.Answer__c, rule); 

                    if(!shouldAssign) {
                        break; 
                    }

                }

            }

        }

        if(shouldAssign) {

            response.OwnerId__c = assignment.Assign__c;

        }

    }

    public static Boolean operateOnAnswer(String answer, Clarity_Form_Assignment_Rule__c rule) {

        Boolean shouldAssign = false; 

        if(rule.Operator__c == 'Equals') {
            shouldAssign = answer == rule.Value__c ? true : false; 
        }

        if(rule.Operator__c == 'Not Equal') {
            shouldAssign = answer != rule.Value__c ? true : false; 
        }

        if(rule.Operator__c == 'Is Not Null') {
            shouldAssign = answer != null ? true : false; 
        }

        if(rule.Operator__c == 'Is Greater than or equal to') {
            shouldAssign = Integer.valueOf(answer) >= Integer.valueOf(rule.Value__c) ? true : false; 
        }

        if(rule.Operator__c == 'Is Less than or equal to') {
            shouldAssign = Integer.valueOf(answer) >= Integer.valueOf(rule.Value__c) ? true : false; 
        }

        return shouldAssign;

    }

}