mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                    <default>true</default>
                    <label>Create</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Record_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Group</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Record Groups</relationshipLabel>
        <relationshipName>Clarity_Form_Questions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/controllers/helpers/RecordsHelper.cls
public with sharing class RecordsHelper {
	
	public static List<sObject> getRecords(List<Form_Connection__c> formConnections, List<Response_Connection__c> responseConnections, Response__c response) {

		List<sObject> records = new List<sObject>(); 

		Map<Id, Response_Connection__c> responseConnectionById = new Map<Id, Response_Connection__c>(); 

        for(Response_Connection__c responseConnection : responseConnections) {
            responseConnectionById.put(responseConnection.Form_Connection__c, responseConnection);
        }

		for(Form_Connection__c formConnection : formConnections) {
	
			List<String> sFields = new List<String>(); 

			Response_Connection__c responseConnection = responseConnectionById.get(formConnection.Id); 

			Map<String, Form_Connection_Field__c> uniqueFields = new Map<String, Form_Connection_Field__c>(); 

			for(Form_Connection_Field__c field : formConnection.Form_Connection_Fields__r) {
				uniqueFields.put(field.Salesforce_Field__c, field);
			}

			for(Form_Connection_Field__c field : uniqueFields.values()) {
				if(field.Salesforce_Field__c != 'Id' && field.Salesforce_Field__c != 'Name' && field.Salesforce_Field__c != 'Subject') {
					sFields.add(field.Salesforce_Field__c);
				}
			}

			String joinedFields = '';

			if(sFields.size() > 0) {
				joinedFields = String.join(sFields, ', ');
				joinedFields = joinedFields.removeEnd(',');
				if(joinedFields != null && joinedFields != '') {
					joinedFields = ', ' + joinedFields;
				}
			} 

			String record = responseConnection.Record__c;

			String returningField = 'Name';

			if(formConnection.Salesforce_Object__c == 'Case') {
				returningField = 'Subject';
			}

			sObject result = Database.query('SELECT Id, ' + returningField + ' ' + joinedFields + ' FROM ' + formConnection.Salesforce_Object__c + ' WHERE Id = :record LIMIT 1');

			records.add(result);
		}

		return records; 

	}

	public static Map<Id, List<sObject>> getRecordGroupSubmissions(List<Answer__c> answers, List<Question__c> questions) {

        Map<Id, List<sObject>> recordGroupSubmissions = new Map<Id, List<sObject>>();

        Map<String, Set<String>> recordGroupFields = new Map<String, Set<String>>(); 
		

        //get the field names by sboject
        for(Question__c question : questions) {

            if(question.Record_Group__c != null) {

                String sObjectName = question.Record_Group__r.Salesforce_Object__c;

                Id recordGroupId = question.Record_Group__c; 

                String field = question.Salesforce_Field__c;

				Schema.SObjectType convertType = Schema.getGlobalDescribe().get(sObjectName);

				Map<String, Schema.SObjectField> sObjectFields = convertType.getDescribe().fields.getMap();

				Boolean access = sObjectFields.get(field).getDescribe().isAccessible();

                if(recordGroupFields.get(sObjectName) != null && access) {

                    recordGroupFields.get(sObjectName).add(field);

                } else if(access) {

                    recordGroupFields.put(sObjectName, new Set<String>{ field });

                }

            }
        }

        Map<String, Set<String>> recordIdsBySObjectName = new Map<String, Set<String>>(); 

        Map<String, Set<String>> recordIdsByRecordGroupId = new Map<String, Set<String>>(); 

        Map<Id, Id> recordGroupIdByRecordId = new Map<Id, Id>();

        //get the recordIds created by sobject name that way we can query for them
        //we will also need to be able to know which recordIds belong to which record group/question ids
        //ability to get sbojectname by recordgroupid
        for(Answer__c answer : answers) {

            if(answer.Question__r.Type__c == 'RecordGroup') {

                Id recordId = answer.Record__c; 
                Id recordGroupId = answer.Question__c; 
                String sObjectName = answer.Question__r.Salesforce_Object__c;

                if(recordIdsBySObjectName.get(sObjectName) != null) {

                    recordIdsBySObjectName.get(sObjectName).add(recordId);

                } else {

                    recordIdsBySObjectName.put(sObjectName, new Set<String>{ recordId });

                }

                if(recordIdsByRecordGroupId.get(recordGroupId) != null) {

                    recordIdsByRecordGroupId.get(recordGroupId).add(recordId);

                } else {

                    recordIdsByRecordGroupId.put(recordGroupId, new Set<String>{ recordId });

                }

                recordGroupIdByRecordId.put(recordId, recordGroupId); 

            }
        }

        //need to be able to query for sobject recordIds only once and assign results to map by questionId/recordGroupId
        for(String sObjectName : recordGroupFields.keySet()) {

            List<String> sFields = new List<String>(recordGroupFields.get(sObjectName));

            Set<String> recordIds = recordIdsBySObjectName.get(sObjectName);

            String joinedFields = '';

            if(sFields.size() > 0) {
                joinedFields = String.join(sFields, ', ');
                joinedFields = joinedFields.removeEnd(',');
                joinedFields = ', ' + joinedFields;
            } 

            List<sObject> results = Database.query('SELECT Id ' + joinedFields + ' FROM ' + sObjectName + ' WHERE Id IN :recordIds WITH SECURITY_ENFORCED');

            for(sObject result : results) {

                Id recordGroupId = recordGroupIdByRecordId.get(result.Id); 

                if(recordGroupSubmissions.get(recordGroupId) != null) {
                    
                    recordGroupSubmissions.get(recordGroupId).add(result); 

                } else {

                    recordGroupSubmissions.put(recordGroupId, new List<sObject> { result }); 

                }

            }

        }

        return recordGroupSubmissions;

    }

}