mdapi-source/updated-package/objects/Answer__c.object
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <displayFormat>CFA-{0000}</displayFormat>
        <label>Clarity Form Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContentDocument__c</fullName>
        <label>ContentDocument</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentVersion__c</fullName>
        <label>ContentVersion</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Answer__c</fullName>
        <label>Date Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/AnswersSelector.cls
public class AnswersSelector extends fflib_SObjectSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Answer__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Answer__c.Id,
			Answer__c.Name,
			Answer__c.Answer__c,
			Answer__c.Response__c,
			Answer__c.ContentDocument__c,
			Answer__c.ContentVersion__c,
			Answer__c.Date_Answer__c,
			Answer__c.Record__c
		};
	}

	public List<Answer__c> selectById(Set<Id> recordIds){
		return (List<Answer__c>) selectSObjectsById(recordIds);
	}

	public static IAnswersSelector newInstance(){
		return (IAnswersSelector) Application.selector.newInstance(Answer__c.SObjectType);
	}
 
}