mdapi-source/updated-package/objects/Checklist_Group__c.object
<CustomObject>
    <label>Clarity Checklist Group</label>
    <nameField>
        <label>Checklist Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Checklist Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Checklist_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Checklist Group</label>
        <referenceTo>Checklist_Group__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/ChecklistGroupsSelector.cls
public class ChecklistGroupsSelector extends fflib_SObjectSelector implements IChecklistGroupsSelector {
  public Schema.SObjectType getSObjectType() {
    return Checklist_Group__c.sObjectType;
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Checklist_Group__c.Id,
      Checklist_Group__c.Name,
      Checklist_Group__c.Standard__c
    };
  }

  public List<Checklist_Group__c> selectById(Set<Id> recordIds) {
    return (List<Checklist_Group__c>) selectSObjectsById(recordIds);
  }

  public List<Checklist_Group__c> selectGroups() {
    fflib_QueryFactory query = newQueryFactory();

    return (List<Checklist_Group__c>) Database.query(query.toSOQL());
  }

  public List<Checklist_Group__c> selectByIdWithForms(Set<Id> recordIds) {
    fflib_QueryFactory query = newQueryFactory();

    query.setCondition('Id IN :recordIds');

    new FormsSelector().addQueryFactorySubselect(query, 'cforms__Forms__r');

    return (List<Checklist_Group__c>) Database.query(query.toSOQL());
  }

  public static IChecklistGroupsSelector newInstance() {
    return (IChecklistGroupsSelector) Application.selector.newInstance(
      Checklist_Group__c.SObjectType
    );
  }
}