mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/restapi/ResponsesResourceUnitTest.cls
@isTest
public class ResponsesResourceUnitTest {

	@TestSetup
	public static void setup(){
		
		User user = TestDataFactory.generateUserWithBuilderPermissions(); 

		System.runAs(user) {

			Form__c form = TestDataFactory.generateForm(); 

			Form__c updatedForm = FormsService.updateForm(form);

			List<Question__c> newQuestions = TestDataFactory.generateQuestions(new List<Form__c>{ form });

			List<Question__c> questions = QuestionsService.saveQuestions(newQuestions);

			updatedForm.Status__c = 'Published';

			Form__c publishedForm = FormsService.updateForm(updatedForm);

			Response__c response = ResponseController.createResponse( publishedForm.Id, JSON.serialize(new Map<String, String>()) );

			Response__c response2 = ResponseController.createResponse( publishedForm.Id, JSON.serialize(new Map<String, String>()) );

		}
	}

	@isTest
	public static void shouldDeleteResponses() {
		
		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];

		System.runAs(user) {

			List<Response__c> responses = [SELECT Id, UUID__c FROM Response__c];

			System.assertEquals(2, responses.size());

			List<String> uuids = new List<String>();

			for(Response__c response : responses) {
				uuids.add(response.UUID__c);
			}

			RestRequest request = new RestRequest();

			request.httpMethod = 'DELETE';
			request.requestBody = Blob.valueOf(JSON.serialize(uuids));

			RestContext.request = request;

			ResponsesResource.deleteResponses();

			Test.startTest();

				List<Response__c> afterDelete = [SELECT Id FROM Response__c];

			Test.stopTest();

			System.assertEquals(0, afterDelete.size());

		}

	}

	@isTest
	public static void shouldUpdateResponses() {

				
		User user = [SELECT Id FROM USER WHERE UserName = 'test_cl@clarityforms.io' Limit 1];

		System.runAs(user) {

			Form__c existingForm = [SELECT Id FROM Form__c LIMIT 1];

			Id existingFormId = existingForm.Id; 
			
			Map<String, String> data = new Map<String, String>();

			List<Response> responses = new List<Response>();

			for (Integer i = 0; i < 5; i++) {
				
				Response response = new Response();

				response.OwnerId = UserInfo.getUserId();
				response.Status = 'In Progress';
				response.UUID = 'TEST-123' + i;
				response.Form = existingFormId;

				responses.add(response);

			}

			data.put('data', JSON.serialize(responses));

			RestRequest request = new RestRequest();

			request.httpMethod = 'POST';
			request.requestBody = Blob.valueOf(JSON.serialize(data));

			RestContext.request = request;

			ResponsesResource.updateResponses();

			Test.startTest();

				List<Response__c> updatedResponses = [SELECT Id FROM Response__c];

			Test.stopTest();

			System.assertEquals(7, updatedResponses.size());

		}

	}

}