mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Custom_Value__c</fullName>
        <label>Custom Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PreFill__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreFill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/FormConnectionFieldsSelector.cls
public with sharing class FormConnectionFieldsSelector extends fflib_SObjectSelector implements IFormConnectionFieldsSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Form_Connection_Field__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Form_Connection_Field__c.Id,
			Form_Connection_Field__c.Name,
			Form_Connection_Field__c.Form_Connection__c,
			Form_Connection_Field__c.Question__c,
			Form_Connection_Field__c.Custom_Value__c,
			Form_Connection_Field__c.PreFill__c,
			Form_Connection_Field__c.Salesforce_Field__c
	   };
	}

	public List<Form_Connection_Field__c> selectFieldsByConnectionId(String connectionId){
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Form_Connection__c = :connectionId');
		return (List<Form_Connection_Field__c>) Database.query( query.toSOQL() );
	}

	public List<Form_Connection_Field__c> selectFieldsByConnectionId(Set<Id> connectionIds){
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Form_Connection__c IN :connectionIds');
		return (List<Form_Connection_Field__c>) Database.query( query.toSOQL() );
	}

	public static IFormConnectionFieldsSelector newInstance(){
		return (IFormConnectionFieldsSelector) Application.selector.newInstance(Form_Connection_Field__c.SObjectType);
	}
}