mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Has_Thank_You__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Thank You</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Multi_Page_Info__c</fullName>
        <defaultValue>&quot;[]&quot;</defaultValue>
        <label>Multi Page Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Multi_Page_Val__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multi Page Val</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multi_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multi Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thank_You_Redirect__c</fullName>
        <label>Thank You Redirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Criteria__c.object
<CustomObject>
    <label>Clarity Form Question Criteria</label>
    <nameField>
        <label>Clarity Form Question Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clarity_Form_Question_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                </value>
                <value>
                    <fullName>Greater than</fullName>
                </value>
                <value>
                    <fullName>Less than</fullName>
                </value>
                <value>
                    <fullName>Is Greater than or equal to</fullName>
                </value>
                <value>
                    <fullName>Is Less than or equal to</fullName>
                </value>
                <value>
                    <fullName>Is not</fullName>
                </value>
                <value>
                    <fullName>Is Not Null</fullName>
                </value>
                <value>
                    <fullName>Not Equal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Criteria</relationshipLabel>
        <relationshipName>Question_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Option__c.object
<CustomObject>
    <label>Clarity Form Question Option</label>
    <nameField>
        <label>Clarity Form Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Choice_Image__c</fullName>
        <label>Choice Image</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Clarity_Form_Question_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MultipleChoice</fullName>
    </customValue>
    <customValue>
        <fullName>Comment</fullName>
    </customValue>
    <customValue>
        <fullName>Star</fullName>
    </customValue>
    <customValue>
        <fullName>Dropdown</fullName>
    </customValue>
    <customValue>
        <fullName>Ranking</fullName>
    </customValue>
    <customValue>
        <fullName>NetPromoterScore</fullName>
    </customValue>
    <customValue>
        <fullName>Slider</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Lookup</fullName>
    </customValue>
    <customValue>
        <fullName>RecordGroup</fullName>
    </customValue>
    <customValue>
        <fullName>Image</fullName>
    </customValue>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Attachments</fullName>
    </customValue>
    <customValue>
        <fullName>ConnectedObject</fullName>
    </customValue>
    <description>Question Types Currently Available</description>
    <masterLabel>Clarity Form Question Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/selectors/FormsSelector.cls
public class FormsSelector extends fflib_SObjectSelector implements IFormsSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Form__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Form__c.Id,
			Form__c.Name,
			Form__c.Title__c,
			Form__c.Status__c,
			Form__c.CreatedDate,
			Form__c.Multi_Page__c,
			Form__c.CreatedById.Name,
			Form__c.Has_Thank_You__c,
			Form__c.Thank_You_Redirect__c,
			Form__c.Limit__c,
			Form__c.Multi_Page_Val__c,
			Form__c.Multi_Page_Info__c,
			Form__c.End_Date__c
	   };
	}

	public List<Form__c> selectById(Set<Id> recordIds){
		return (List<Form__c>) selectSObjectsById(recordIds);
	}

	public List<Form__c> selectWithResponseItems(){
		fflib_QueryFactory query = newQueryFactory().selectField('CreatedById.Name');

		new QuestionsSelector().
			addQueryFactorySubselect(query,'forms__Questions__r');

		new ResponsesSelector().
			  addQueryFactorySubselect(query,'forms__Responses__r').selectField('CreatedById.Name').selectField('Form__c.Title__c');
   
		return (List<Form__c>) Database.query( query.toSOQL() );
	}  

	public static IFormsSelector newInstance(){
		return (IFormsSelector) Application.selector.newInstance(Form__c.SObjectType);
	}
}

// (SELECT Id, Label__c, Active_Flow__c, Choice_Image__c, Order__c FROM Question_Options__r), 
// (SELECT Id, Field_Type__c, Field__c, Operator__c, Type__c, Value__c, Question__c FROM Question_Criteria__r),