mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Connection__c/fields/Form_Version__c.field-meta.xml
<CustomField>
    <fullName>Form_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Version</label>
    <referenceTo>Form_Version__c</referenceTo>
    <relationshipLabel>Clarity Form Connections</relationshipLabel>
    <relationshipName>Clarity_Form_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Version__c/Form_Version__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Form_Version__c.field-meta.xml
<CustomField>
    <fullName>Form_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Version</label>
    <referenceTo>Form_Version__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/services/FormConnectionsServiceImpl.cls
public class FormConnectionsServiceImpl implements IFormConnectionsService {
  public List<Form_Connection__c> getConnectionsByResponseId(
    String responseId
  ) {
    List<Form_Connection__c> requiredConnections = new List<Form_Connection__c>();

    List<Response__c> response = ResponsesSelector.newInstance()
      .selectById(new Set<Id>{ responseId });

    List<Form_Connection__c> allFormConnections = FormConnectionsSelector.newInstance()
      .selectConnectionsByFormVersionId(response[0].Form_Version__c);

    Set<Id> connectionIds = new Set<Id>();

    for (Form_Connection__c connection : allFormConnections) {
      connectionIds.add(connection.Id);
    }

    List<Response_Connection__c> responseConnections = ResponseConnectionsSelector.newInstance()
      .selectResponseConnectionsByConnectionIds(connectionIds, responseId);

    if (responseConnections.size() == 0) {
      return allFormConnections;
    }

    Set<Id> responseConnectedIds = new Set<Id>();

    for (Response_Connection__c responseConnection : responseConnections) {
      responseConnectedIds.add(responseConnection.Form_Connection__c);
    }

    for (Form_Connection__c connection : allFormConnections) {
      if (!responseConnectedIds.contains(connection.Id)) {
        requiredConnections.add(connection);
      }
    }

    return requiredConnections;
  }

  public List<Form_Connection__c> getConnectionsByFormVersionId(
    String formVersionId
  ) {
    List<Form_Connection__c> connections = FormConnectionsSelector.newInstance()
      .selectConnectionsByFormVersionId(formVersionId);
    return connections;
  }

  public List<Form_Connection__c> getConnectionsByFormVersionIds(
    Set<Id> formVersionIds
  ) {
    List<Form_Connection__c> connections = FormConnectionsSelector.newInstance()
      .selectConnectionsByFormVersionIds(formVersionIds);
    return connections;
  }

  public List<Form_Connection__c> save(
    List<Form_Connection__c> removedConnections,
    List<Form_Connection__c> newConnections
  ) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    uow.registerDeleted(removedConnections);

    uow.registerUpsert(newConnections);

    uow.commitWork();

    return newConnections;
  }
}