mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Result_Holder__c</fullName>
        <label>Result Holder</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                    <default>true</default>
                    <label>Create</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/FormConnectionsSelector.cls
public with sharing class FormConnectionsSelector extends fflib_SObjectSelector implements IFormConnectionsSelector {
  public Schema.SObjectType getSObjectType() {
    return Form_Connection__c.sObjectType;
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Form_Connection__c.Id,
      Form_Connection__c.Name,
      Form_Connection__c.New__c,
      Form_Connection__c.Result_Holder__c,
      Form_Connection__c.Salesforce_Object__c,
      Form_Connection__c.Type__c,
      Form_Connection__c.Form__c
    };
  }

  public List<Form_Connection__c> selectConnectionsByResponseId(
    String responseId
  ) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Form__c = :formId AND New__c = true');
    return (List<Form_Connection__c>) Database.query(query.toSOQL());
  }

  public List<Form_Connection__c> selectConnectionsByFormIds(Set<Id> formIds) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Form__c IN :formIds');

    return (List<Form_Connection__c>) Database.query(query.toSOQL());
  }

  public List<Form_Connection__c> selectConnectionsByFormId(String formId) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Form__c = :formId');

    new FormConnectionFieldsSelector()
      .addQueryFactorySubselect(query, 'cforms__Form_Connection_Fields__r');

    return (List<Form_Connection__c>) Database.query(query.toSOQL());
  }

  public List<Form_Connection__c> selectConnectionsByFormStatus(String status) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Form__r.Status__c = :status');

    new FormConnectionFieldsSelector()
      .addQueryFactorySubselect(query, 'cforms__Form_Connection_Fields__r');

    return (List<Form_Connection__c>) Database.query(query.toSOQL());
  }

  public static IFormConnectionsSelector newInstance() {
    return (IFormConnectionsSelector) Application.selector.newInstance(
      Form_Connection__c.SObjectType
    );
  }
}