mdapi-source/updated-package/objects/Form_Connection_Process__c.object
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/services/ResponseProcessService.cls
public with sharing class ResponseProcessService {
  public static void saveConnectionProcess(
    Form_Connection_Process__c connectionProcess
  ) {
    service().saveConnectionProcess(connectionProcess);
  }

  public static void saveResponse(List<Response__c> responses) {
    service().saveResponse(responses);
  }

  public static IResponseProcessService service() {
    return (IResponseProcessService) Application.service.newInstance(
      IResponseProcessService.class
    );
  }
}