mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Version__c/Form_Version__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Version__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <description>Parent of Form Versions</description>
    <label>Clarity Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Versions</relationshipLabel>
    <relationshipName>Form_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Form_Version__c.field-meta.xml
<CustomField>
    <fullName>Form_Version__c</fullName>
    <label>Clarity Form Version</label>
    <referenceTo>Form_Version__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/selectors/FormVersionsSelector.cls
public class FormVersionsSelector extends fflib_SObjectSelector implements IFormVersionsSelector {
  public Schema.SObjectType getSObjectType() {
    return Form_Version__c.sObjectType;
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{ Form__c.Id, Form__c.Name };
  }

  public List<Form_Version__c> selectById(Set<Id> recordIds) {
    return (List<Form_Version__c>) selectSObjectsById(recordIds);
  }

  public List<Form_Version__c> selectByFormId(Id formId) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Form__c = :formId');

    new QuestionsSelector()
      .addQueryFactorySubselect(query, 'cforms__Questions__r');

    return (List<Form_Version__c>) Database.query(query.toSOQL());
  }

  public static IFormVersionsSelector newInstance() {
    return (IFormVersionsSelector) Application.selector.newInstance(
      Form_Version__c.SObjectType
    );
  }
}