mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/controllers/FormSummaryController.cls
public with sharing class FormSummaryController {

	//create response from lightning
	@AuraEnabled
	public static Id newResponse(String formName){
		
		Form__c form = FormsService.getFormByName(formName); 
		Response__c response = ResponsesService.create(form.Id); 

		return response.Id; 

	}
	
    @AuraEnabled
    public static Form__c getForm(String recordId) {

		Form__c form = FormsService.getFormById(recordId); 

		return form; 

    }

    @AuraEnabled
    public static List<Response__c> getFormResponses(String recordId){

		List<Response__c> responses = ResponsesService.getResponsesByFormId(recordId);

        return responses; 

    }

    @AuraEnabled
    public static String deleteFormResponse(String recordId){

		Id responseId = ResponsesService.deleteById(recordId);
        
        return responseId;
    }

    @AuraEnabled
    public static String deleteForm(String recordId){

		Id formId = FormsService.deleteById(recordId);

        return formId;

	}

    @AuraEnabled
    public static Form__c publishForm(String recordId){

		Form__c form = FormsService.publishForm(recordId); 

	    return form;

    }

    @AuraEnabled(cacheable=true)
    public static  Map<String, List<Map<String, String>>> getAnswerColumns(String recordId, Integer offset){

		Map<String, List<Map<String, String>>> table = ResponsesService.getResultAnswersByFormId(recordId, offset); 

        return table;

    }
    
}