mdapi-source/updated-package/objects/Form_Connection_Process__c.object
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Form Connection Process</relationshipLabel>
        <relationshipName>Form_Connection_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesforce_Connection_Object__c</fullName>
        <label>Salesforce Connection Object</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/domains/ResponsesUnitofWorkHelper.cls
public class ResponsesUnitofWorkHelper implements fflib_SObjectUnitOfWork.IDoWork
{       
    public Database.UpsertResult[] ResponseResults {get; private set;}
	public Database.UpsertResult ConnectionProcessResult {get; private set;}

	private sObject connection_record;
	private List<Response__c> responses;
	private Form_Connection_Process__c connection_status;

    public ResponsesUnitofWorkHelper()
    {  
		responses = new List<Response__c>();
		connection_record = null;
		connection_status = null;
    }
     
    public void registerResponseConnections(sObject srecord, List<Response__c> records, Form_Connection_Process__c connectionStatus)
    {
		System.debug('errors: ' + srecord);
		responses.addAll(records);
		connection_record = srecord;
		connection_status = connectionStatus;
	}
     
    public void doWork()
    {	
		if(connection_record == null) {

			connection_status.Status__c = 'Failed';
			connection_status.Description__c = connection_record.Id;
	
			ConnectionProcessResult = Database.upsert(connection_status, false);  

			return; 

		}

		String genericObjectName = connection_record.getSObjectType().getDescribe().getName();

		Schema.SObjectType responseType = Schema.Response__c.getSObjectType();

		Map<String, Schema.SObjectField> responseSObjectFields = responseType.getDescribe().fields.getMap();

		String connectedName = 'forms__' + genericObjectName + '__c'; 

		List<Response__c> updateResponses = new List<Response__c>();

		for(Response__c response : responses) {

			Response__c newResponse = (Response__c)Schema.Response__c.getSObjectType().newSObject(response.Id); 
			newResponse.put(connectedName, connection_record.Id);
			updateResponses.add(newResponse);

		}

		ResponseResults = Database.upsert(updateResponses, false);  

		connection_status.Status__c = 'Success';
		connection_status.Salesforce_Connection_Object__c = connection_record.Id;

		ConnectionProcessResult = Database.upsert(connection_status, false);  
               
    }
}