mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/controllers/SetupControllerUnitTest.cls
@isTest
public class SetupControllerUnitTest {
	
	@TestSetup
	public static void setup(){
		
		Form__c form = TestDataFactory.generateForm(); 
		
		List<Question__c> newQuestions = TestDataFactory.generateQuestions(new List<Form__c>{ form });

		BuilderController.save(JSON.serialize(newQuestions));
		
	}

	@isTest
	public static void shouldGetSetup() {

	}

	@isTest
	public static void shouldCreateConnect() {
		
	}

	@isTest
	public static void shouldRegisterUsers() {
		
	}

}