mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/validations/ConnectionFieldValidationTest.cls
/**
 * @author ben@clarityforms.io
 * @company Clarity Forms
 * @date 05/16/2019
 *
 * @group Form_Connection_Field__c
 *
 * @description On update of Form_Connection__c, if salesforce object was changed delete Form_Connection_Field__c records
 */
@isTest
public class ConnectionFieldValidationTest {
  @testSetup
  public static void setup() {
    User user = TestDataFactory.generateUserWithBuilderPermissions();

    System.runAs(user) {
      Form__c form = TestDataFactory.generateForm();

      List<Question__c> questions = TestDataFactory.generateQuestions(
        new List<Form__c>{ form }
      );

      List<Question__c> savedQuestions = QuestionsService.saveQuestions(
        questions
      );

      List<Form_Connection__c> connections = TestDataFactory.generateConnections(
        true,
        form.Id,
        new List<String>{ 'Account' }
      );

      List<Form_Connection__c> connectionsSaved = FormConnectionsService.save(
        new List<Form_Connection__c>(),
        connections
      );

      List<Form_Connection_Field__c> customFields = TestDataFactory.generateCustomConnectionFields(
        connections[0].Id,
        new Map<String, String>{ 'Name' => 'Testing' }
      );

      List<Form_Connection_Field__c> customFieldsSaved = FormConnectionFieldsService.updateFields(
        customFields,
        connections[0].Id
      );
    }

  }

  @isTest
  public static void shouldDeleteFieldOnConnectionUpdate() {
    User user = [
      SELECT Id
      FROM USER
      WHERE UserName = 'test_cl@clarityforms.io'
      LIMIT 1
    ];

    System.runAs(user) {
      Form_Connection__c connection = [SELECT Id FROM Form_Connection__c];

      List<Form_Connection_Field__c> beforeFields = [
        SELECT Id
        FROM Form_Connection_Field__c
      ];

      System.assertEquals(1, beforeFields.size());

      Test.startTest();

      connection.Salesforce_Object__c = 'Case';

      List<Form_Connection__c> connectionsSaved = FormConnectionsService.save(
        new List<Form_Connection__c>(),
        new List<Form_Connection__c>{ connection }
      );

      Test.stopTest();

      List<Form_Connection_Field__c> afterFields = [
        SELECT Id
        FROM Form_Connection_Field__c
      ];

      System.assertEquals(0, afterFields.size());
    }

  }
}