mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question_Option__c.object
<CustomObject>
    <label>Clarity Form Question Option</label>
    <nameField>
        <label>Clarity Form Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/tests/controllers/BuilderControllerUnitTest.cls
@isTest
public class BuilderControllerUnitTest {
	
	@TestSetup
	static void setup(){
		
	}


    @isTest
    public static void shouldSave() {

	}

    @isTest
    public static void shouldGetForm() {

    }
		
	@isTest
    public static void shouldUpdateForm() {

	}
	
	@isTest
    public static void shouldGetQuestions() {

    }
		
	@isTest
    public static void shouldSaveQuestion() {

	}
	
	@isTest
    public static void shouldSaveQuestionWithOptions() {

		// Form__c form = [SELECT Id FROM Form__c LIMIT 1];

		// List<Question__c> expectedQuestions = [SELECT Id FROM Question__c WHERE Type__c = 'Dropdown']; 

		// List<Question_Option__c> optionsCreate = TestDataFactory.generateQuestionOptions(expectedQuestions);

		// String sQuestion = JSON.serialize(expectedQuestions[0]); 

		// String sQuestionOptions = JSON.serialize(optionsCreate); 

		// Test.startTest();

        // Map<String, List<sObject>> options = BuilderController.saveQuestionWithOptions(sQuestion, sQuestionOptions);

		// Test.stopTest();

		// System.assertEquals(1, options.get('Options').size());
		
	}
	
	@isTest
    public static void shouldSaveQuestionWithCriteria() {

	}
	
	@isTest
    public static void shouldSaveRecordGroupFields() {

	}
	
	@isTest
    public static void shouldGetConnections() {

    }
		
	@isTest
    public static void shoulGetConnectionFieldMapping() {

	}
	
	@isTest
    public static void shoulSaveConnections() {

	}
	
	@isTest
    public static void shoulSaveActiveFieldConnections() {

	}
	
	@isTest
    public static void shoulDeletePageQuestions() {

	}
	
	@isTest
    public static void shoulDeleteQuestion() {

	}
	
	@isTest
    public static void shoulGetSObjectsAvailable() {

    }
		

}