mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/domains/helpers/ConnectionFieldValidation.cls
/**
 * @author efigenio.ben@clarityforms.io
 * @company Clarity Forms
 * @date 05/16/2019
 *
 * @group Form_Connection_Field__c
 *
 * @description On update of Form_Connection__c, if salesforce object was changed delete Form_Connection_Field__c records
 */
public class ConnectionFieldValidation {
  public static Map<Id, List<Form_Connection_Field__c>> ConnectionFields {
    get {
      if (ConnectionFields == null) {
        ConnectionFields = new Map<Id, List<Form_Connection_Field__c>>();

        List<Form_Connection_Field__c> fields = FormConnectionFieldsSelector.newInstance()
          .selectFieldsByConnectionId(Trigger.newMap.keySet());

        for (Form_Connection_Field__c field : fields) {
          if (ConnectionFields.get(field.Form_Connection__c) == null) {
            ConnectionFields.put(
              field.Form_Connection__c,
              new List<Form_Connection_Field__c>{ field }
            );
          } else {
            ConnectionFields.get(field.Form_Connection__c).add(field);
          }
        }
      }

      return ConnectionFields;
    }
    set;
  }
}