mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response__c.object
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/updated-package/objects/Response_Connection__c.object
<CustomObject>
    <label>Clarity Form Response Connection</label>
    <nameField>
        <label>Clarity Form Response Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Response Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Clarity Form Response</label>
        <referenceTo>Response__c</referenceTo>
        <relationshipLabel>Response Connections</relationshipLabel>
        <relationshipName>Response_Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/ResponseConnectionsSelector.cls
public with sharing class ResponseConnectionsSelector extends fflib_SObjectSelector implements IResponseConnectionsSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Response_Connection__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Response_Connection__c.Id,
			Response_Connection__c.Name,
			Response_Connection__c.Form_Connection__c,
			Response_Connection__c.Response__c,
			Response_Connection__c.Record__c
	   };
	}
	
	public List<Response_Connection__c> selectResponseConnectionsByConnectionIds(Set<Id> connectionIds, String responseId){
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Form_Connection__c IN :connectionIds AND Id = :responseId');
		return (List<Response_Connection__c>) Database.query( query.toSOQL() );
	}

	public List<Response_Connection__c> getByResponseId(Set<Id> responseIds){
		fflib_QueryFactory query = newQueryFactory();
		query.setCondition('Response__c IN :responseIds');
		return (List<Response_Connection__c>) Database.query( query.toSOQL() );
	}

	public static IResponseConnectionsSelector newInstance(){
		return (IResponseConnectionsSelector) Application.selector.newInstance(Response_Connection__c.SObjectType);
	}
}