mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection__c.object
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Connections</relationshipLabel>
        <relationshipName>Form_Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Form_Connection_Field__c.object
<CustomObject>
    <label>Clarity Form Connection Field</label>
    <nameField>
        <label>Clarity Form Connection Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Custom_Value__c</fullName>
        <label>Custom Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Connection__c</fullName>
        <label>Clarity Form Connection</label>
        <referenceTo>Form_Connection__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PreFill__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PreFill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clarity Form Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Form Connection Fields</relationshipLabel>
        <relationshipName>Form_Connection_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <label>Clarity Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/services/FormsService.cls
public with sharing class FormsService {

	
	public static Map<String, Map<String, sObject>> getMobileRecords() {

		Map<String, Map<String, sObject>> records = new Map<String, Map<String, sObject>>(); 

		List<Form__c> forms = [SELECT Id FROM Form__c WHERE Status__c = 'Published'];

		List<Id> formIds = new List<Id>(); 

		for (Form__c form : forms) {
			formIds.add(form.Id); 
		}

		List<Form_Connection__c> formConnections = [SELECT Id, Form__c, Salesforce_Object__c, New__c, 
		(SELECT Id, Salesforce_Field__c, PreFill__c, Custom_Value__c, Question__c FROM Form_Connection_Fields__r) 
		FROM Form_Connection__c WHERE Form__c IN :formIds];


		Map<String, Set<String>> objectFields = new Map<String, Set<String>>(); 

		for(Form_Connection__c formConnection : formConnections) {

			for(Form_Connection_Field__c field : formConnection.Form_Connection_Fields__r) {
							
				if(objectFields.get(formConnection.Salesforce_Object__c) != null) {

					Set<String> fields = objectFields.get(formConnection.Salesforce_Object__c); 
					fields.add(field.Salesforce_Field__c);
					objectFields.put(formConnection.Salesforce_Object__c, fields); 

				} else {

					Set<String> fields = new Set<String>();

					if(formConnection.Salesforce_Object__c == 'Case') {
						fields.add('Subject');
					} else {
						fields.add('Name');
					}

					fields.add('Id');
					fields.add(field.Salesforce_Field__c);
					
					objectFields.put(formConnection.Salesforce_Object__c, fields); 

				}
            }
			
		}

		Integer limitCount = 0;

		for(String objectName : objectFields.keySet()) {

			if(limitCount > 10) {
				continue; 
			}

			List<String> sFields = new List<String>(); 

			Set<String> fields = objectFields.get(objectName); 

			String joinedFields = '';

			for(String field : fields) {
				sFields.add(field);
			}

			if(sFields.size() > 0) {
				joinedFields = String.join(sFields, ', ');
				joinedFields = joinedFields.removeEnd(',');
			} 
			System.debug('joinedFields: ' + joinedFields); 
			String sQuery = 'SELECT ' + joinedFields + ' FROM ' + objectName + ' LIMIT 50';

			List<sObject> results = Database.query(sQuery);

			Map<String, sObject> sObjectRecords = new Map<String, sObject>(); 

			for(SObject result : results) {
				sObjectRecords.put(result.Id, result);
			} 

			records.put(objectName, sObjectRecords);

			limitCount = limitCount + 1; 

		}

		return records;
	}

	public static List<Form__c> getForms() {
		return service().getForms();
	}

	public static Form__c getFormById(String formId) {
		return service().getFormById(formId);
	}

	public static Form__c updateForm(Form__c form) {
		return service().updateForm(form);
	}

	public static IFormsService service(){
		return (IFormsService) Application.service.newInstance(IFormsService.class);
	}
}