mdapi-source/updated-package/objects/Form__c.object
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Clarity Forms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Active_Form_Version__c.field-meta.xml
<CustomField>
    <fullName>Active_Form_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Active Form Version</label>
    <referenceTo>Form_Version__c</referenceTo>
    <relationshipLabel>Clarity Forms</relationshipLabel>
    <relationshipName>Clarity_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Version__c/Form_Version__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Version__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <description>Parent of Form Versions</description>
    <label>Clarity Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Versions</relationshipLabel>
    <relationshipName>Form_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/services/FormVersionsServiceImpl.cls
public class FormVersionsServiceImpl implements IFormVersionsService {
  public Form_Version__c updateFormVersion(Form_Version__c formVersion) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(
      new fflib_SecureDML()
    );

    uow.registerUpsert(formVersion);
    uow.commitWork();

    return formVersion;
  }

  public List<Form_Version__c> getFormVersionsByFormId(String formId) {
    List<Form_Version__c> formVersions = FormVersionsSelector.newInstance()
      .selectByFormId(formId);
    return formVersions;
  }

  public Form_Version__c getFormVersionById(String formVersionId) {
    List<Form_Version__c> formVersions = FormVersionsSelector.newInstance()
      .selectById(new Set<Id>{ formVersionId });
    return formVersions[0];
  }

  public List<Form_Version__c> getFormVersionsByIds(Set<Id> formVersionIds) {
    List<Form_Version__c> formVersions = FormVersionsSelector.newInstance()
      .selectById(formVersionIds);
    return formVersions;
  }

  public Form_Version__c getActiveFormVersionByFormId(String formId) {
    List<Form__c> forms = FormsSelector.newInstance()
      .selectById(new Set<Id>{ formId });
    if (forms.size() == 0) {
      // throw new Exception('No forms with Id');
    }
    Form__c form = forms[0];
    List<Form_Version__c> formVersions = FormVersionsSelector.newInstance()
      .selectById(new Set<Id>{ form.Active_Form_Version__c });
    return formVersions[0];
  }
}