mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/services/helpers/PicklistHelper.cls
public class PicklistHelper {
	
	public static List<Picklist> getValues(List<Question__c> questions) {

		List<Picklist> allPicklists = new List<Picklist>(); 

		Map<String, List<String>> picklistQuestions = new Map<String, List<String>>(); 

		for(Question__c question : questions) {

			if(question.Type__c == 'PICKLIST') {

				if(picklistQuestions.containsKey(question.Salesforce_Object__c)) {
					picklistQuestions.get(question.Salesforce_Object__c).add(question.Salesforce_Field__c);
				} else {
					picklistQuestions.put(question.Salesforce_Object__c, new List<String>{  question.Salesforce_Field__c });
				}
			}

		}
		

		for(String sObjectName : picklistQuestions.keySet()) {

			SObjectType sObjType = ((SObject)Type.forName(objectType).newInstance()).getSObjectType();

			Schema.DescribeSObjectResult result = sObjType.getDescribe();
	
			Map<String, Schema.SObjectField> fields = result.fields.getMap();

			List<String> picklists = picklistQuestions.get(sObjectName); 

			for(String picklist: picklists) {

				Picklist pl = new Picklist(); 

				pl.sObject = sObjectName;
				pl.Name = picklist; 
				pl.PicklistValues = new List<PicklistValue>();

				Schema.DescribeFieldResult fieldResult = fields.get(picklist).getDescribe();

				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

				for(Schema.PicklistEntry pickListVal : ple){

					PicklistValue plv = new Picklist(); 

					plv.Label = pickListVal.getLabel();
					plv.APIName = pickListVal.getValue();
					
					pl.PicklistValues.add(plv); 
					
				}

				allPicklists.add(pl); 

			}

		}

		return allPicklists; 

	}
	
}