mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Record_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Group</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Record Groups</relationshipLabel>
        <relationshipName>Clarity_Form_Questions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Field__c</fullName>
        <label>Salesforce Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <label>Salesforce Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MultipleChoice</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
                <value>
                    <fullName>Dropdown</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>RecordGroup</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachments</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>COMBOBOX</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ANYTTYPE</fullName>
                </value>
                <value>
                    <fullName>BASE64</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>ENCRYPTEDSTRING</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LONG</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/controllers/helpers/PicklistHelper.cls
public with sharing class PicklistHelper {

	public static Map<String, List<String>> filterRecordGroupPicklist(List<Question__c> questions) {

        Map<String, List<String>> salesforceObjectFields = new Map<String, List<String>>(); 

        for(Question__c question : questions) {
            if(question.Record_Group__c != null && question.Type__c == 'PICKLIST') {

                if(salesforceObjectFields.get(question.Record_Group__r.Salesforce_Object__c) != null) {
                    salesforceObjectFields.get(question.Record_Group__r.Salesforce_Object__c).add(question.Salesforce_Field__c);
                } else {
                    salesforceObjectFields.put(question.Record_Group__r.Salesforce_Object__c, new List<String>{ question.Salesforce_Field__c });
                }

            }
        }

        return salesforceObjectFields;
    }

    public static Map<String, Map<String, Map<String, String>>> getSalesforcePicklistValues(Map<String, List<String>> salesforceObjectFields) {
        
        Map<String, Map<String, Map<String, String>>> values = new Map<String, Map<String, Map<String, String>>>(); 

        List<String> salesforceObjects = new List<String>(salesforceObjectFields.keySet());

        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(salesforceObjects);

        for(Schema.DescribeSobjectResult res : results) {

            List<String> fields = salesforceObjectFields.get(res.getName()); 

            Map<String, Map<String, String>> fieldPicklistValues = new Map<String, Map<String, String>>(); 

            for(String field : fields) {

                List<Schema.PicklistEntry> entries = res.fields.getMap().get(field).getDescribe().getPicklistValues();
                
                Map<String, String> picklistValues = new Map<String, String>();

                for(Schema.PicklistEntry entry : entries) {
	                if (entry.isActive()) {
                        picklistValues.put(entry.getValue(), entry.getLabel());
                    }
                }

                fieldPicklistValues.put(field, picklistValues);

            }

            values.put(res.getName(), fieldPicklistValues);

        }

        return values;

    }

}