mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/controllers/helpers/Question.cls
global class Question implements Comparable {
  public Question__c question;

  public Question(Question__c q) {
    question = q;
  }

  global Integer compareTo(Object compareTo) {
    Question compareToQuestion = (Question) compareTo;

    Integer returnValue = 0;
    if (question.Order__c > compareToQuestion.question.Order__c) {
      returnValue = 1;
    } else if (question.Order__c < compareToQuestion.question.Order__c) {
      returnValue = -1;
    }

    return returnValue;
  }
}