mdapi-source/updated-package/objects/Question_Option__c.object
<CustomObject>
    <label>Clarity Form Question Option</label>
    <nameField>
        <label>Clarity Form Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/selectors/QuestionOptionsSelector.cls
public class QuestionOptionsSelector extends fflib_SObjectSelector {
 
	public Schema.SObjectType getSObjectType(){
	   return Question_Option__c.sObjectType;
	}
  
	public List<Schema.SObjectField> getSObjectFieldList(){
	   return new List<Schema.SObjectField> {
			Question_Option__c.Id,
			Question_Option__c.Name,
			Question_Option__c.Label__c
		};
	}

	public List<Question_Option__c> selectById(Set<Id> recordIds){
		return (List<Question_Option__c>) selectSObjectsById(recordIds);
	}

	public static IQuestionOptionsSelector newInstance(){
		return (IQuestionOptionsSelector) Application.selector.newInstance(Question_Option__c.SObjectType);
	}
 
}