force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question_Flow_Design__c/Clarity_Form_Question_Flow_Design__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question Flow Design</label>
    <nameField>
        <label>Clarity Form Question Flow Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Question Flow Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question_Flow_Design__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>forms__Form_Question__c</fullName>
    <label>Clarity Form Question</label>
    <referenceTo>forms__Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Question Flow Designs</relationshipLabel>
    <relationshipName>forms__Form_Question_Flow_Designs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question_Flow_Design__c/fields/Form_Submission__c.field-meta.xml
<CustomField>
    <fullName>Form_Submission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Submission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuestionFlowDesigns.cls
/**
* @author efigenio.ben@clarityforms.io
* @company Clarity Forms
* @date 05/16/2019
*
* @group Clarity_Form_Question_Flow_Design__c
*
* @description 1 record of object Clarity_Form_Question_Flow_Design__c for each question - Currently No Checks
*/
public class QuestionFlowDesigns {

    public static void execute(List<Clarity_Form_Question_Flow_Design__c> flowDesignsToBeCreated, Clarity_Form_Question__c cf) {

        Clarity_Form_Question_Flow_Design__c flow = new Clarity_Form_Question_Flow_Design__c(
            Clarity_Form_Question__c = cf.Id, 
            Form_Submission__c       = false, 
            Active__c                = false
        );

        flowDesignsToBeCreated.add(flow); 

    }

}