force-app/main/default/objects/Clarity_Survey_Response__c/Clarity_Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Survey Response</label>
    <nameField>
        <label>Clarity Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Survey_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Response Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaritySurveyHandler.cls
public class ClaritySurveyHandler {

    public class Clarity {

        public String recordId; 

        public String type;

        public Integer rating;  

        public String status;  

    }

    public static void log(String res) {

        List<Clarity> cltys = (List<Clarity>)JSON.deserialize(res, List<Clarity>.class); 

        List<Clarity_Survey_Response__c> surveys = new List<Clarity_Survey_Response__c>(); 

        for (Clarity clty : cltys) {

            surveys.add(
                new Clarity_Survey_Response__c(
                    //Case__c   = clty.recordId,
                    Status__c =  clty.status 
                )
            );

        }

        insert surveys; 
        
    }
}