force-app/main/default/objects/Flow_Design__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Clarity Form Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Flow Designs</relationshipLabel>
    <relationshipName>Flow_Designs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi-source/updated-package/objects/Question__c.object
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <displayFormat>CFQ-{0000}</displayFormat>
        <label>Clarity Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/builders/QuestionFlowDesigns.cls
/**
* @author efigenio.ben@clarityforms.io
* @company Clarity Forms
* @date 05/16/2019
*
* @group Flow_Design__c
*
* @description 1 record of object Flow_Design__c for each question - Currently No Checks
*/
public class QuestionFlowDesigns {

    public static void execute(List<Flow_Design__c> flowDesignsToBeCreated, Question__c cf) {

        Flow_Design__c flow = new Flow_Design__c(
            Question__c = cf.Id, 
            Form_Submission__c       = false, 
            Active__c                = false
        );

        flowDesignsToBeCreated.add(flow); 

    }

}