force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection__c/Clarity_Form_Connection__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Connection</label>
    <nameField>
        <label>Clarity Form Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Connection__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Connections</relationshipLabel>
    <relationshipName>Clarity_Form_Connections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection_Process__c/Clarity_Form_Connection_Process__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Connection Process</label>
    <nameField>
        <displayFormat>CFCP-{0000}</displayFormat>
        <label>Clarity Form Connection Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Connection Process</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Connection_Process__c/fields/Clarity_Form_Connection__c.field-meta.xml
<CustomField>
    <fullName>forms__Form_Connection__c</fullName>
    <label>Clarity Form Connection</label>
    <referenceTo>forms__Form_Connection__c</referenceTo>
    <relationshipLabel>Clarity Form Connection Process</relationshipLabel>
    <relationshipName>forms__Form_Connection_Process</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Connection_Process__c/fields/Clarity_Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Response__c</fullName>
    <label>Clarity Form Response</label>
    <referenceTo>Clarity_Form_Response__c</referenceTo>
    <relationshipLabel>Clarity Form Connection Process</relationshipLabel>
    <relationshipName>Clarity_Form_Connection_Process</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MultipleChoice</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Star</fullName>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
            <value>
                <fullName>Ranking</fullName>
            </value>
            <value>
                <fullName>NetPromoterScore</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>RecordGroup</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>ConnectedObject</fullName>
            </value>
            <value>
                <fullName>BOOLEAN</fullName>
            </value>
            <value>
                <fullName>DATETIME</fullName>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
            </value>
            <value>
                <fullName>COMBOBOX</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>ANYTTYPE</fullName>
            </value>
            <value>
                <fullName>BASE64</fullName>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
            </value>
            <value>
                <fullName>INTEGER</fullName>
            </value>
            <value>
                <fullName>LONG</fullName>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
            </value>
            <value>
                <fullName>PERCENT</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConnectionRecordProcessTest.cls
@isTest
public class ConnectionRecordProcessTest {

    @testSetup
    public static void setup(){
                
        List<Clarity_Form__c> forms = ClarityTestDataFactory.generateForms(5);

        List<Clarity_Form_Question__c> questions = ClarityTestDataFactory.generateQuestions(forms);
		//response 1 prep
        List<Clarity_Form_Connection__c> connections = ClarityTestDataFactory.generateConnections(true, forms[0], new List<String>{ 'Opportunity' });

        ClarityTestDataFactory.generateConnectionFields(connections[0], new Map<String, Id>{'ForecastCategoryName' =>  questions[0].Id });

        ClarityTestDataFactory.publishForm(forms[0]);

		Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(forms[0]);
		//response 2 prep
		List<Clarity_Form_Connection__c> connections2 = ClarityTestDataFactory.generateConnections(true, forms[1], new List<String>{ 'Opportunity' });

        ClarityTestDataFactory.generateCustomConnectionFields(connections2[0], new Map<String, String>{ 'Name' => 'Custom Name', 'StageName' => 'Prospecting', 'CloseDate' => '07/22/2030' });

        ClarityTestDataFactory.publishForm(forms[1]);

		Clarity_Form_Response__c response2 = ClarityTestDataFactory.generateResponse(forms[1]);

        ClarityTestDataFactory.generateAnswers(response2, questions);
		
		//response 3 prep
        List<Clarity_Form_Connection__c> connections3 = ClarityTestDataFactory.generateConnections(true, forms[2], new List<String>{ 'Opportunity', 'Contact' });

        ClarityTestDataFactory.generateCustomConnectionFields(connections3[0], new Map<String, String>{ 'Name' => 'Custom Name', 'StageName' => 'Prospecting', 'CloseDate' => '07/22/2030' });

        ClarityTestDataFactory.generateCustomConnectionFields(connections3[1], new Map<String, String>{ 'FirstName' => 'Clarity', 'LastName' => 'Developer' });

        ClarityTestDataFactory.publishForm(forms[2]);

        Clarity_Form_Response__c response3 = ClarityTestDataFactory.generateResponse(forms[2]);

        ClarityTestDataFactory.generateAnswers(response3, questions);

        Clarity_Form_Question__c question = [SELECT Id, Type__c, Title__c FROM Clarity_Form_Question__c WHERE Type__c = 'Comment' AND Clarity_Form__c =: forms[2].Id LIMIT 1];

		ClarityTestDataFactory.updateAnswer(response3, question);

		//response 4 prep
        List<Clarity_Form_Connection__c> connections4 = ClarityTestDataFactory.generateConnections(true, forms[3], new List<String>{ 'Opportunity' });

        List<Clarity_Form_Question__c> questions4 = [SELECT Id, Type__c, Title__c FROM Clarity_Form_Question__c WHERE Type__c = 'Comment' AND Clarity_Form__c =: forms[3].Id];

        ClarityTestDataFactory.generateConnectionFields(connections4[0], new Map<String, String>{ 'Name' => questions4[0].Id });

        ClarityTestDataFactory.generateCustomConnectionFields(connections4[0], new Map<String, String>{ 'StageName' => 'Prospecting', 'CloseDate' => '07/22/2030' });

        ClarityTestDataFactory.publishForm(forms[3]);

        Clarity_Form_Response__c response4 = ClarityTestDataFactory.generateResponse(forms[3]);

        ClarityTestDataFactory.generateAnswers(response4, questions4);
		
		//response 5 prep
        List<Clarity_Form_Connection__c> connections5 = ClarityTestDataFactory.generateConnections(true, forms[4],  new List<String>{ 'Account', 'Opportunity' });

        ClarityTestDataFactory.generateCustomConnectionFields(connections5[0], new Map<String, String>{ 'Name' => 'Custom Account Name' });

        ClarityTestDataFactory.generateCustomConnectionFields(connections5[1], new Map<String, String>{ 'Name' => 'Custom Opportunity Name', 'StageName' => 'Prospecting', 'CloseDate' => '07/22/2030', 'AccountId' => '{Connection_Account}' });

        ClarityTestDataFactory.publishForm(forms[4]);

        Clarity_Form_Response__c response5 = ClarityTestDataFactory.generateResponse(forms[4]);

        List<Clarity_Form_Question__c> questions5 = [SELECT Id,  Type__c, Title__c FROM Clarity_Form_Question__c WHERE Type__c = 'Comment' AND Clarity_Form__c =: forms[4].Id];

        ClarityTestDataFactory.generateAnswers(response5, questions5);
    }

    @isTest
    public static void shouldUpdateProcessToFailed() {
        
        ConnectionCreateJob.chainJob = false;

        List<Clarity_Form_Response__c> responses = [SELECT Id, Name, Status__c, Clarity_Form__c FROM Clarity_Form_Response__c];

		Clarity_Form_Response__c response = responses[0];

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

			Database.SaveResult result = Database.update(responses[0], true); 

			if(!result.isSuccess()) {
				System.debug('error');
			}
        
        Test.stopTest(); 

		List<Opportunity> opportunities = [SELECT Id, ForecastCategoryName FROM Opportunity];

        List<Clarity_Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Clarity_Form_Connection_Process__c WHERE Clarity_Form_Response__c =: response.Id]; 

        for(Clarity_Form_Connection_Process__c process : connectionProcess) {
            System.assertEquals('Failed', process.Status__c); 
        }

        System.assertEquals(opportunities.size(), 0);

    }

    @isTest
    public static void shouldCreateOpportunityConnectionFromCustomValue() {

        ConnectionCreateJob.chainJob = false;

        List<Clarity_Form_Response__c> responses = [SELECT Id, Status__c FROM Clarity_Form_Response__c];

		Clarity_Form_Response__c response = responses[1];

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

			Database.SaveResult result = Database.update(response, true); 

			if(!result.isSuccess()) {
				System.debug('error');
			}
        
        Test.stopTest(); 

        List<Clarity_Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Clarity_Form_Connection_Process__c]; 

        for(Clarity_Form_Connection_Process__c process : connectionProcess) {
            System.assertEquals('Success', process.Status__c); 
        }

        List<Opportunity> opportunities = [SELECT Id FROM Opportunity];

        System.assertEquals(opportunities.size(), 1);
    }

    @isTest
    public static void shouldCreateMultipleConnectionsFromCustomValues(){

        ConnectionCreateJob.chainJob = false;

        List<Clarity_Form_Response__c> responses = [SELECT Id, Status__c FROM Clarity_Form_Response__c];

		Clarity_Form_Response__c response = responses[2];

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

            update response; 
        
        Test.stopTest(); 

        List<Clarity_Form_Connection_Process__c> connectionProcess = [SELECT Id, Status__c FROM Clarity_Form_Connection_Process__c]; 

        for(Clarity_Form_Connection_Process__c process : connectionProcess) {
            System.assertEquals('Success', process.Status__c); 
        }

        List<Opportunity> opportunities = [SELECT Id FROM Opportunity];

        System.assertEquals(1, opportunities.size());

        List<Contact> contacts = [SELECT Id FROM Contact];

        System.assertEquals(1, contacts.size());

    }

    @isTest
    public static void shouldCreateOpportunityConnectionFromQuestionValue() {

        ConnectionCreateJob.chainJob = false;

        List<Clarity_Form_Response__c> responses = [SELECT Id, Status__c, Clarity_Form__c FROM Clarity_Form_Response__c];

		Clarity_Form_Response__c response = responses[3];

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

            update response; 
        
        Test.stopTest(); 

        List<Clarity_Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Clarity_Form_Connection_Process__c WHERE Clarity_Form_Response__c =: response.Id]; 

        for(Clarity_Form_Connection_Process__c process : connectionProcess) {
            System.assertEquals('Success', process.Status__c); 
        }

        List<Opportunity> opportunities = [SELECT Id, Name FROM Opportunity];

        System.assertEquals(1, opportunities.size());

    }

    @isTest
    public static void shouldCreateMultipleConnectionsWithAppropriateStoreIds(){

        ConnectionCreateJob.chainJob = false;

        List<Clarity_Form_Response__c> responses = [SELECT Id, Status__c, Clarity_Form__c FROM Clarity_Form_Response__c];

		Clarity_Form_Response__c response = responses[4];

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

            update response; 
        
        Test.stopTest(); 

        List<Clarity_Form_Connection_Process__c> connectionProcess = [SELECT Id, Salesforce_Connection_Object__c, Status__c FROM Clarity_Form_Connection_Process__c WHERE Clarity_Form_Response__c =: response.Id]; 

        for(Clarity_Form_Connection_Process__c process : connectionProcess) {
            System.assertEquals('Success', process.Status__c); 
        }

        List<Account> accounts = [SELECT Id FROM Account];

        System.assertEquals(accounts.size(), 1);

        List<Opportunity> opportunities = [SELECT Id, AccountId FROM Opportunity];

        System.assertEquals(opportunities.size(), 1);

        System.assertEquals(accounts[0].Id, opportunities[0].AccountId);

    }

}