force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MultipleChoice</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Star</fullName>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
            <value>
                <fullName>Ranking</fullName>
            </value>
            <value>
                <fullName>NetPromoterScore</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>RecordGroup</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>ConnectedObject</fullName>
            </value>
            <value>
                <fullName>BOOLEAN</fullName>
            </value>
            <value>
                <fullName>DATETIME</fullName>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
            </value>
            <value>
                <fullName>COMBOBOX</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>ANYTTYPE</fullName>
            </value>
            <value>
                <fullName>BASE64</fullName>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
            </value>
            <value>
                <fullName>INTEGER</fullName>
            </value>
            <value>
                <fullName>LONG</fullName>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
            </value>
            <value>
                <fullName>PERCENT</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClarityFormBuilder.cls
global with sharing class ClarityFormBuilder {
	
    public class Question {
        public String title { get; set; }
        public Integer order  { get; set; }
        public String type  { get; set; }
        public String formId  { get; set; }
    }

    @RemoteAction
    global static List<String> save(String sQuestions){

        List<String> saved = new List<String>(); 

        List<Question> parsedQuestions = (List<Question>)JSON.deserialize(sQuestions, List<Question>.class);

        List<Clarity_Form_Question__c> clarityQuestions = new List<Clarity_Form_Question__c>(); 

        for(Question question : parsedQuestions) {

            Clarity_Form_Question__c newQuestion = new Clarity_Form_Question__c(
                Clarity_Form__c = question.formId,
                Title__c        = question.title, 
                Type__c         = question.type, 
                Order__c        = question.order
            );
            
            clarityQuestions.add(newQuestion); 

        }

        List<Database.SaveResult> results = Database.insert(clarityQuestions, true); 

        for(Database.SaveResult result : results) {

            if(result.isSuccess()) {
                saved.add(result.getId());
            }

        }

        return saved; 
    }

    @RemoteAction 
    global static String createForm(){

        Clarity_Form__c form = new Clarity_Form__c(
            Name = 'Clarity Form'
        );

        Database.SaveResult result = Database.insert(form); 

        if(!result.isSuccess()) {
            //throw error
        }

        return result.getId(); 

    }
}