force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/fields/Clarity_Form_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Assignment</label>
    <referenceTo>Clarity_Form_Assignment__c</referenceTo>
    <relationshipLabel>Clarity Forms</relationshipLabel>
    <relationshipName>Clarity_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Assignment__c/Clarity_Form_Assignment__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Assignment</label>
    <nameField>
        <label>Clarity Form Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MultipleChoice</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Star</fullName>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
            <value>
                <fullName>Ranking</fullName>
            </value>
            <value>
                <fullName>NetPromoterScore</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>RecordGroup</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>ConnectedObject</fullName>
            </value>
            <value>
                <fullName>BOOLEAN</fullName>
            </value>
            <value>
                <fullName>DATETIME</fullName>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
            </value>
            <value>
                <fullName>COMBOBOX</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>ANYTTYPE</fullName>
            </value>
            <value>
                <fullName>BASE64</fullName>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
            </value>
            <value>
                <fullName>INTEGER</fullName>
            </value>
            <value>
                <fullName>LONG</fullName>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
            </value>
            <value>
                <fullName>PERCENT</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OwnerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FormResponseAssignmentTest.cls
@isTest
public class FormResponseAssignmentTest {

    @testSetup
    public static void setup(){
                
        Clarity_Form__c form = ClarityTestDataFactory.generateForm();

        List<Clarity_Form_Question__c> questions = ClarityTestDataFactory.generateQuestions(form);

    }

    @isTest
    public static void shouldAssignFormToUserCreated() {

        Clarity_Form__c form = [SELECT Id, Status__c FROM Clarity_Form__c];

        Clarity_Form_Question__c question = [SELECT Id, Type__c, Title__c FROM Clarity_Form_Question__c WHERE Type__c = 'Comment' LIMIT 1];

        User u = ClarityTestDataFactory.generateUser();

        Clarity_Form_Assignment__c assignment = ClarityTestDataFactory.generateAssignment(form, u, 'AND');

        ClarityTestDataFactory.generateAssignmentRules(assignment.Id, new List<Clarity_Form_Question__c> { question }, 'Comment');

        ClarityTestDataFactory.publishForm(form);

        Clarity_Form_Response__c response = ClarityTestDataFactory.generateResponse(form);

        ClarityTestDataFactory.updateAnswer(response, question);

        System.assertEquals(response.OwnerId__c, null);

        Test.startTest();       
            
            response.Status__c = 'Submitted'; 

            update response; 
        
        Test.stopTest(); 

        Clarity_Form_Response__c submittedResponse = [SELECT Id, OwnerId__c FROM Clarity_Form_Response__c Limit 1];

        //System.assertEquals(submittedResponse.OwnerId__c, u.Id);

    }

}