force-app/main/default/objects/Clarity_Form__c/Clarity_Form__c.object-meta.xml
<CustomObject>
    <description>Forms designed by Salesforce Administrators.</description>
    <label>Clarity Form</label>
    <nameField>
        <label>Clarity Forms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/Clarity_Form_Answer__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Answer</label>
    <nameField>
        <label>Clarity Form Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarity Form Question</label>
    <referenceTo>Clarity_Form_Question__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Answer__c/fields/Clarity_Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form_Response__c</fullName>
    <label>Clarity Form Response</label>
    <referenceTo>Clarity_Form_Response__c</referenceTo>
    <relationshipLabel>Clarity Form Answers</relationshipLabel>
    <relationshipName>Clarity_Form_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Question__c/Clarity_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Question</label>
    <nameField>
        <label>Clarity Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarity Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Question__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Questions</relationshipLabel>
    <relationshipName>Clarity_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/Clarity_Form_Response__c.object-meta.xml
<CustomObject>
    <label>Clarity Form Response</label>
    <nameField>
        <displayFormat>CFR-{0000}</displayFormat>
        <label>Clarity Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarity Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Clarity_Form__c.field-meta.xml
<CustomField>
    <fullName>Clarity_Form__c</fullName>
    <label>Clarity Form</label>
    <referenceTo>Clarity_Form__c</referenceTo>
    <relationshipLabel>Clarity Form Responses</relationshipLabel>
    <relationshipName>Clarity_Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clarity_Form_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateResponseAnswers.cls
/**
* @author efigenio.ben@clarityforms.io
* @company Clarity Forms
* @date 07/22/2019
*
* @group Clarity_Form_Response__c
*
* @description On insert of Clarity_Form_Response__c create an answer for each question.
*/
public class CreateResponseAnswers {

    private static Map<Id, List<Clarity_Form_Question__c>> FormQuestions {
        get {

            if(FormQuestions == null) {

                FormQuestions = new Map<Id,  List<Clarity_Form_Question__c>>();

                List<Id> formIds = new List<Id>();

                for(Clarity_Form_Response__c response : (List<Clarity_Form_Response__c>)Trigger.new) {
                    formIds.add(response.Clarity_Form__c);
                }

                List<Clarity_Form_Question__c> questions = [SELECT Id, Clarity_Form__c FROM Clarity_Form_Question__c WHERE Clarity_Form__c IN :formIds];

                for(Clarity_Form_Question__c question : questions) { 

                    if(FormQuestions.get(question.Clarity_Form__c) != null) {
                        
                        FormQuestions.get(question.Clarity_Form__c).add(question);

                    } else {

                        FormQuestions.put(question.Clarity_Form__c, new List<Clarity_Form_Question__c>{ question });

                    }

                }

            }
            
            return FormQuestions;
        }
        set; 
    }

    public static void execute(List<Clarity_Form_Answer__c> answersToBeCreated, Clarity_Form_Response__c response) {
        
        if(response.Status__c != 'New') return; 
                
        if(FormQuestions.get(response.Clarity_Form__c) == null) return; 

        List<Clarity_Form_Question__c> questions = FormQuestions.get(response.Clarity_Form__c); 

        for(Clarity_Form_Question__c question : questions) {
            Clarity_Form_Answer__c answer = new Clarity_Form_Answer__c(
                Clarity_Form_Response__c = response.Id, 
                Clarity_Form_Question__c = question.Id
            );

            answersToBeCreated.add(answer);
        }

    }

}